export default {
  app: { title: 'Gestor de frases' },
  snackbar: {
    selectParentCategoryFirst: 'Selecciona primero un grupo', categoryDeleted: 'Categoría eliminada', categoryNameExists: 'Ya existe una categoría con este nombre', categoryCreated: 'Categoría creada', categoryUpdated: 'Categoría actualizada', groupNameExists: 'Ya existe un grupo con este nombre', groupCreated: 'Grupo creado', groupUpdated: 'Grupo actualizado', groupDeleted: 'Grupo eliminado', noGroup: 'Crea o selecciona primero un grupo', undone: 'Acción deshecha', redone: 'Acción rehecha',
    noChanges: 'No hay cambios que guardar', duplicatePhrase: 'Ya existe una frase idéntica', phraseCreated: 'Frase creada', phraseUpdated: 'Cambios guardados', phraseDeleted: 'Frase eliminada', titleEmpty: 'El título no puede estar vacío', contentEmpty: 'El contenido está vacío', saveFailed: 'No se pudo guardar. Inténtalo de nuevo.', copiedToClipboard: 'Copiado al portapapeles', createCategoryFirst: 'Crea primero una categoría', itemsDeleted: { one: 'Se ha eliminado {count} elemento', other: 'Se han eliminado {count} elementos' }, phrasesMoved: { one: 'Se ha movido {count} frase', other: 'Se han movido {count} frases' }, movedToTop: 'Movido al principio', movedToBottom: 'Movido al final', batchMovedToTop: 'Los elementos seleccionados se han movido al principio', batchMovedToBottom: 'Los elementos seleccionados se han movido al final', phraseCloned: 'Frase duplicada', clonedToCategory: 'Copiado a la categoría nueva', movedToCategory: 'Movido a la categoría nueva',
    categoryCopiedToGroup: 'Categoría copiada al grupo nuevo', categoryMovedToGroup: 'Categoría movida al grupo nuevo', categoriesCopiedToGroup: { one: 'Se ha copiado {count} categoría al grupo nuevo', other: 'Se han copiado {count} categorías al grupo nuevo' }, categoriesMovedToGroup: { one: 'Se ha movido {count} categoría al grupo nuevo', other: 'Se han movido {count} categorías al grupo nuevo' }, copiedToUncategorized: 'Copiado a «Sin categoría»', movedToUncategorized: 'Movido a «Sin categoría»', phrasesCopiedToUncategorized: { one: 'Se ha copiado {count} frase a «Sin categoría»', other: 'Se han copiado {count} frases a «Sin categoría»' }, phrasesMovedToUncategorized: { one: 'Se ha movido {count} frase a «Sin categoría»', other: 'Se han movido {count} frases a «Sin categoría»' },
    exportSuccess: 'Exportación completada', exportFailed: 'No se ha podido exportar: {error}', importSuccess: 'Importación completada. Categorías: {categories}; frases: {phrases}', importFailed: 'No se ha podido importar: {error}', batchExportSuccess: 'Exportación completada. Categorías: {categories}; frases: {phrases}', iflytekImportSuccess: 'Importación desde el método de entrada iFlytek completada. Categorías: {categories}; frases: {phrases}', iflytekExportSuccess: 'Se ha exportado en el formato del método de entrada iFlytek', batchMovedToGroup: 'Movido al grupo. Categorías: {categories}; frases: {phrases}', guideCompleted: '¡Has terminado el tutorial! Hemos añadido datos de ejemplo para que puedas explorar la aplicación.', cloudUpdatedDraftPreserved: 'Los datos de la nube se han actualizado. El borrador actual no se ha sobrescrito.'
  },
  tooltip: { newCategory: 'Nueva categoría (Ctrl+Mayús+N)', newPhrase: 'Nueva frase (Ctrl+N)', help: 'Ayuda', switchToLight: 'Tema claro', switchToDark: 'Tema oscuro', import: 'Importar', export: 'Exportar', sort: 'Ordenar', batchMode: 'Selección múltiple', selectAll: 'Seleccionar todo / Borrar selección', moveToCategory: 'Mover a una categoría', moveToTop: 'Mover al principio', moveToBottom: 'Mover al final', delete: 'Eliminar', exit: 'Salir', clone: 'Duplicar', edit: 'Editar', newGroup: 'Nuevo grupo', fullscreen: 'Editor a pantalla completa', exitFullscreen: 'Salir de pantalla completa', exitEdit: 'Cerrar el editor', settings: 'Ajustes' },
  menu: { rename: 'Cambiar nombre', moveToTop: 'Mover al principio', moveToBottom: 'Mover al final', delete: 'Eliminar', copyContent: 'Copiar contenido', clone: 'Duplicar', edit: 'Editar', sortCustom: 'Orden personalizado', sortUsageDesc: 'Más usadas primero', sortUsageAsc: 'Menos usadas primero', sortCreatedDesc: 'Más recientes primero', sortCreatedAsc: 'Más antiguas primero', sortUpdatedDesc: 'Editadas recientemente primero', sortUpdatedAsc: 'Editadas hace más tiempo primero', sortTitleAsc: 'Título (A–Z)', sortTitleDesc: 'Título (Z–A)', newGroup: 'Nuevo grupo…', newCategory: 'Nueva categoría…', exportNative: 'Exportar como JSON', exportIflytek: 'Exportar para el método de entrada iFlytek' },
  label: { group: 'Grupo', category: 'Categoría', title: 'Título', content: 'Contenido' }, placeholder: { searchPhrase: 'Buscar frases…' }, empty: { noCategories: 'Todavía no hay categorías', quickJump: 'Ir a una categoría', noResults: 'No hay coincidencias', noPhrases: 'Todavía no hay frases', noGroups: 'Todavía no hay grupos', uncategorized: 'Sin categoría' },
  defaults: { groupName: 'Nuevo grupo', newGroup: 'Nuevo grupo', categoryName: 'Nueva categoría', newCategory: 'Nueva categoría', uncategorized: 'Sin categoría', newPhrase: 'Nueva frase', copySuffix: ' (copia)', iflytekGroupName: 'Desde el método de entrada iFlytek', importGroupName: 'Datos importados' },
  dialog: { unsavedChanges: 'Cambios sin guardar', unsavedContent: 'Este contenido no se ha guardado. ¿Quieres guardar los cambios?', unsavedContentNote: 'Los cambios que no guardes se perderán.', discard: 'Descartar', thinkAgain: 'Seguir editando', save: 'Guardar', exportTitle: 'Exportar copia de seguridad de frases', exportIflytekTitle: 'Exportar para el método de entrada iFlytek', importTitle: 'Importar copia de seguridad de frases', jsonFilter: 'Archivos JSON', csvFilter: 'Archivos CSV', allSupportedFilter: 'Archivos compatibles' },
  count: { categories: { one: '{count} categoría', other: '{count} categorías' }, characters: { one: '{count} carácter', other: '{count} caracteres' }, selected: { one: '{count} elemento seleccionado', other: '{count} elementos seleccionados' }, batchSelected: 'Selección: {categories} categorías; {phrases} frases' }, section: { groups: 'Grupos de frases' }, file: { backupName: 'copia-frases-{date}.json', iflytekBackupName: 'copia-frases-{date}.csv' },
  common: { cancel: 'Cancelar', apply: 'Aplicar', close: 'Cerrar', copy: 'Copiar', listSeparator: ', ', groupSeparator: '; ', labelSeparator: ': ' },
  settings: { title: 'Ajustes', language: 'Idioma de la interfaz', languageAuto: 'Automático (idioma del sistema)', themeMode: 'Tema', themeLight: 'Claro', themeDark: 'Oscuro', themeAuto: 'Usar el ajuste del sistema', startupSelection: 'Abrir al iniciar', startupLast: 'Última ubicación visitada', startupFirst: 'Primer elemento del orden', previewLinesLabel: 'Líneas de vista previa de las tarjetas', previewLines: 'Líneas de vista previa: {count}', aiModel: 'Modelo de IA', defaultAiModel: 'Modelo predeterminado', aiPrompts: 'Instrucciones para la IA', aiCategorizePrompt: 'Instrucción de clasificación', aiTitlePrompt: 'Instrucción para el título', aiContentPrompt: 'Instrucción para generar contenido', updated: 'Se ha actualizado: {items}' },
  ai: {
    categorize: 'Clasificar con IA', generateTitle: 'Generar título con IA', generateContent: 'Generar contenido con IA', optimizeContent: 'Mejorar contenido con IA', themeGeneration: 'Generar a partir de un tema', newGeneration: 'Crear desde cero', optimizeExisting: 'Mejorar el texto actual', useAsTheme: 'Usar como tema', optimizeDescription: 'La IA hará que el contenido actual sea más claro y profesional.', extraRequirementsLabel: 'Indicaciones adicionales (opcional)', descriptionLabel: 'Describe el contenido que necesitas', extraRequirementsPlaceholder: 'Por ejemplo: usa un tono más formal y añade un agradecimiento…', descriptionPlaceholder: 'Por ejemplo: un correo para rechazar horas extra o un mensaje de agradecimiento a un cliente…', contentApplied: 'Contenido aplicado', generating: 'Generando…', startOptimize: 'Mejorar', generate: 'Generar', inputRequired: 'Escribe primero algún contenido', titleGenerated: 'Título generado', categorized: 'Clasificado en {group} / {category}', categorizedCategory: 'Clasificado en {category}', categoryNotFound: 'No se encuentra la categoría: {category}', groupNotFound: 'No se encuentra el grupo: {group}', noSuggestion: 'La IA no ha encontrado una categoría adecuada', callFailed: 'La solicitud a la IA ha fallado',
    prompt: { optimizeSystem: 'Eres un editor profesional. Mejora el texto del usuario para que sea claro, natural, profesional y esté bien estructurado, sin alterar su significado. Devuelve únicamente el texto revisado, sin comentarios.', themeSystem: 'Eres un asistente de redacción profesional. El usuario proporcionará un texto como tema. Escribe una frase reutilizable nueva, natural y profesional basada en ese tema. Devuelve únicamente el texto nuevo, sin comentarios.', themeUser: 'Tema:\n{content}\n\nEscribe contenido nuevo a partir de este tema.{extra}', extraRequirements: '\nIndicaciones adicionales: {prompt}', generateSystem: 'Eres un asistente de redacción profesional. Escribe una frase reutilizable concisa, natural y profesional a partir de la descripción del usuario. Devuelve únicamente el texto generado, sin comentarios.', categorizeSystem: 'Eres un asistente de clasificación. Elige la categoría más adecuada de la siguiente estructura de grupos y categorías según el contenido.\nEstructura: {structure}\nDevuelve únicamente JSON con este formato exacto: {"分组":"nombre del grupo","分类":"nombre de la categoría"}', titleSystem: 'Eres un asistente para crear títulos. Escribe un título breve y preciso para el contenido, de no más de 15 palabras. Devuelve únicamente el título.' }
  },
  accessibility: { copyPhrase: '{title}. Pulsa Intro para copiar el contenido.' }, dynamic: { group: 'Grupo', category: 'Categoría', phrase: 'Frase', explain: 'Abrir o copiar una frase' }, error: { emptyFile: 'El archivo está vacío', uncaught: 'Error no detectado', unhandledPromise: 'Error asíncrono no controlado', renderTitle: 'Error de renderizado de React' },
  help: {
    sectionHierarchy: '📚 Organización de los datos', hierarchyGroup: 'Grupo', hierarchyGroupDesc: 'Nivel superior', hierarchyCategory: 'Categoría', hierarchyCategoryDesc: 'Carpeta organizativa', hierarchyPhrase: 'Frase', hierarchyPhraseDesc: 'Contenido reutilizable',
    sectionFeatures: '✨ Funciones', featureCopyTitle: 'Copiar con un clic', featureCopyDesc: 'Haz clic en cualquier tarjeta para copiar su contenido al portapapeles y pegarlo donde quieras.', featureEditTitle: 'Edición rápida', featureEditDesc: 'Coloca el puntero sobre una tarjeta y pulsa {key} para editarla al instante.', featureDeleteTitle: 'Eliminar y deshacer', featureDeleteDesc: 'Con el puntero encima, pulsa {delKey} para eliminar o {ctrlKey}+{zKey} para deshacer.', featureDragTitle: 'Arrastrar para mover', featureDragDesc: 'Arrastra una tarjeta a la categoría de destino. Mantén pulsada {key} al arrastrar para copiarla.', featureSearchTitle: 'Buscar en todas partes', featureSearchDesc: 'Busca en todos los grupos y haz clic en un resultado para ir directamente a él.', featureBatchTitle: 'Selección múltiple', featureBatchDesc: 'Usa el icono cuadrado junto al cuadro de búsqueda para seleccionar, eliminar, mover o exportar varios elementos.', featurePreviewTitle: 'Modo de vista previa', featurePreviewDesc: 'Coloca el puntero sobre una tarjeta y pulsa {key} una vez para activar o desactivar la vista previa. Usa las flechas Arriba y Abajo para cambiar de tarjeta.', featureAutoSaveTitle: 'Guardado automático', featureAutoSaveDesc: 'Después de editar, haz clic fuera del editor o cambia de tarjeta para guardar automáticamente.', featureThemeTitle: 'Tema', featureThemeDesc: 'Abre Ajustes para elegir un tema claro u oscuro, o usar el del sistema.',
    sectionShortcuts: '⌨️ Atajos de teclado', shortcutNewPhrase: 'Nueva frase', shortcutNewCategory: 'Nueva categoría', shortcutFocusSearch: 'Ir a la búsqueda', shortcutForceSave: 'Guardar ahora', shortcutUndo: 'Deshacer', shortcutRedo: 'Rehacer', shortcutSelectAll: 'Seleccionar todo (selección múltiple)', shortcutClone: 'Duplicar el elemento señalado', shortcutCopy: 'Copiar el elemento señalado', shortcutEdit: 'Editar el elemento señalado', shortcutDelete: 'Eliminar el elemento señalado', shortcutEscape: 'Salir / Cancelar', shortcutFullscreen: 'Editor a pantalla completa', shortcutPreview: 'Alternar la vista previa', shortcutDragCopy: 'Copiar al destino', dragAction: 'Arrastrar', startGuide: 'Iniciar tutorial'
  },
  guide: {
    steps: {
      step1Title: '🗂️ Grupos (nivel superior)', step1Message: 'Los grupos separan grandes áreas de trabajo.\n\n• {bold:Crear}: haz clic en el botón {key:+} de arriba.\n• {bold:Cambiar}: haz clic en un grupo para mostrar sus categorías.\n• {bold:Ordenar}: mantén pulsado un grupo y arrástralo a izquierda o derecha.\n• {bold:Más}: haz clic con el botón derecho en un grupo para {bold:cambiarle el nombre}, {bold:eliminarlo} o cambiar su posición.',
      step2Title: '📂 Categorías y menú contextual', step2Message: 'Esta columna muestra las categorías del grupo actual.\n\n• {bold:Menú contextual}: haz clic con el botón derecho en una categoría para {bold:cambiarle el nombre}, {bold:moverla al principio} o {bold:eliminarla}.\n• {bold:Cambio de nombre rápido}: selecciona una categoría y pulsa {key:F2}.\n• {bold:Arrastrar y soltar}: arrastra arriba o abajo para ordenar, o suelta la categoría sobre otro grupo para moverla allí.',
      step3Title: '📝 Trabajar con frases', step3Message: 'Este es tu espacio de trabajo principal.\n\n• {bold:Copiar}: haz clic en una tarjeta para copiar su contenido.\n• {bold:Atajos}:\n   - {key:Ctrl} + {key:C} copia\n   - {key:Ctrl} + {key:D} duplica\n   - {key:Supr} elimina el elemento seleccionado\n• {bold:Ordenar}: arrastra las tarjetas arriba o abajo.\n• {bold:Mover entre categorías}: suelta la tarjeta sobre una categoría de la izquierda; mantén {key:Ctrl} al arrastrar para copiarla.\n• {bold:Vista previa}: coloca el puntero sobre una tarjeta, pulsa {key:Espacio} una vez y usa las flechas Arriba y Abajo.',
      step4Title: '🔍 Búsqueda y selección múltiple', step4Message: 'La barra superior permite acceder a todo el contenido.\n\n• {bold:Búsqueda global} ({key:Ctrl} + {key:F}): busca en todos los grupos y haz clic en un resultado para ir a él.\n• {bold:Selección múltiple}: haz clic en el icono cuadrado de la derecha.\n   - Mantén {key:Mayús} para seleccionar un intervalo\n   - Usa la barra inferior para {bold:eliminar}, {bold:mover} o {bold:exportar} los datos seleccionados.',
      step5Title: '⚙️ Copias de seguridad y ajustes', step5Message: 'La barra inferior mantiene a mano las funciones esenciales.\n\n• {bold:Importar / Exportar}: exporta con regularidad una copia JSON para proteger tus datos.\n• {bold:Ajustes}: elige el idioma, el tema, la ubicación de inicio y las líneas de vista previa.\n• {bold:Ayuda}: haz clic en el signo de interrogación para volver a abrir este tutorial.'
    },
    controls: { skip: 'Omitir', back: 'Atrás', next: 'Siguiente', finish: 'Finalizar' },
    demo: { groupName: '✨ Grupo del tutorial', categoryName: '📝 Categoría de ejemplo', phraseTitle: '👋 ¡Te damos la bienvenida!', phraseContent: 'Esta es una frase de ejemplo. Haz clic para copiarla o prueba a arrastrarla.', phraseTitle2: '⌨️ Atajos de teclado', phraseContent2: 'Seleccióname y pulsa Ctrl+C para copiar, Ctrl+D para duplicar o Supr para eliminar.', phraseTitle3: '🖱️ Arrastrar y mover', phraseContent3: 'Mantén pulsado y arrástrame para ordenar, o suéltame sobre otra categoría de la izquierda.' }
  }
}
