export default {
  app: { title: 'Gestionnaire de phrases' },
  snackbar: {
    selectParentCategoryFirst: 'Sélectionnez d’abord un groupe', categoryDeleted: 'Catégorie supprimée', categoryNameExists: 'Une catégorie porte déjà ce nom', categoryCreated: 'Catégorie créée', categoryUpdated: 'Catégorie mise à jour', groupNameExists: 'Un groupe porte déjà ce nom', groupCreated: 'Groupe créé', groupUpdated: 'Groupe mis à jour', groupDeleted: 'Groupe supprimé', noGroup: 'Créez ou sélectionnez d’abord un groupe', undone: 'Action annulée', redone: 'Action rétablie',
    noChanges: 'Aucune modification à enregistrer', duplicatePhrase: 'Une phrase identique existe déjà', phraseCreated: 'Phrase créée', phraseUpdated: 'Modifications enregistrées', phraseDeleted: 'Phrase supprimée', titleEmpty: 'Le titre ne peut pas être vide', contentEmpty: 'Le contenu est vide', saveFailed: 'Échec de l’enregistrement. Réessayez.', copiedToClipboard: 'Copié dans le presse-papiers', createCategoryFirst: 'Créez d’abord une catégorie', itemsDeleted: { one: '{count} élément supprimé', other: '{count} éléments supprimés' }, phrasesMoved: { one: '{count} phrase déplacée', other: '{count} phrases déplacées' }, movedToTop: 'Déplacé en haut', movedToBottom: 'Déplacé en bas', batchMovedToTop: 'Éléments sélectionnés déplacés en haut', batchMovedToBottom: 'Éléments sélectionnés déplacés en bas', phraseCloned: 'Phrase dupliquée', clonedToCategory: 'Copié dans la nouvelle catégorie', movedToCategory: 'Déplacé dans la nouvelle catégorie',
    categoryCopiedToGroup: 'Catégorie copiée dans le nouveau groupe', categoryMovedToGroup: 'Catégorie déplacée dans le nouveau groupe', categoriesCopiedToGroup: { one: '{count} catégorie copiée dans le nouveau groupe', other: '{count} catégories copiées dans le nouveau groupe' }, categoriesMovedToGroup: { one: '{count} catégorie déplacée dans le nouveau groupe', other: '{count} catégories déplacées dans le nouveau groupe' }, copiedToUncategorized: 'Copié dans « Sans catégorie »', movedToUncategorized: 'Déplacé dans « Sans catégorie »', phrasesCopiedToUncategorized: { one: '{count} phrase copiée dans « Sans catégorie »', other: '{count} phrases copiées dans « Sans catégorie »' }, phrasesMovedToUncategorized: { one: '{count} phrase déplacée dans « Sans catégorie »', other: '{count} phrases déplacées dans « Sans catégorie »' },
    exportSuccess: 'Exportation terminée', exportFailed: 'Échec de l’exportation : {error}', importSuccess: 'Importation terminée. Catégories : {categories} ; phrases : {phrases}', importFailed: 'Échec de l’importation : {error}', batchExportSuccess: 'Exportation terminée. Catégories : {categories} ; phrases : {phrases}', iflytekImportSuccess: 'Importation depuis la méthode de saisie iFlytek terminée. Catégories : {categories} ; phrases : {phrases}', iflytekExportSuccess: 'Exporté au format de la méthode de saisie iFlytek', batchMovedToGroup: 'Déplacé vers le groupe. Catégories : {categories} ; phrases : {phrases}', guideCompleted: 'Tutoriel terminé ! Des exemples ont été ajoutés pour vous permettre d’explorer l’application.', cloudUpdatedDraftPreserved: 'Les données du cloud ont été mises à jour. Votre brouillon actuel n’a pas été remplacé.'
  },
  tooltip: { newCategory: 'Nouvelle catégorie (Ctrl+Maj+N)', newPhrase: 'Nouvelle phrase (Ctrl+N)', help: 'Aide', switchToLight: 'Thème clair', switchToDark: 'Thème sombre', import: 'Importer', export: 'Exporter', sort: 'Trier', batchMode: 'Sélection multiple', selectAll: 'Tout sélectionner / Effacer la sélection', moveToCategory: 'Déplacer vers une catégorie', moveToTop: 'Déplacer en haut', moveToBottom: 'Déplacer en bas', delete: 'Supprimer', exit: 'Quitter', clone: 'Dupliquer', edit: 'Modifier', newGroup: 'Nouveau groupe', fullscreen: 'Éditeur plein écran', exitFullscreen: 'Quitter le plein écran', exitEdit: 'Fermer l’éditeur', settings: 'Paramètres' },
  menu: { rename: 'Renommer', moveToTop: 'Déplacer en haut', moveToBottom: 'Déplacer en bas', delete: 'Supprimer', copyContent: 'Copier le contenu', clone: 'Dupliquer', edit: 'Modifier', sortCustom: 'Ordre personnalisé', sortUsageDesc: 'Plus utilisées d’abord', sortUsageAsc: 'Moins utilisées d’abord', sortCreatedDesc: 'Plus récentes d’abord', sortCreatedAsc: 'Plus anciennes d’abord', sortUpdatedDesc: 'Modifiées récemment d’abord', sortUpdatedAsc: 'Modifiées il y a le plus longtemps d’abord', sortTitleAsc: 'Titre (A–Z)', sortTitleDesc: 'Titre (Z–A)', newGroup: 'Nouveau groupe…', newCategory: 'Nouvelle catégorie…', exportNative: 'Exporter au format JSON', exportIflytek: 'Exporter pour la méthode de saisie iFlytek' },
  label: { group: 'Groupe', category: 'Catégorie', title: 'Titre', content: 'Contenu' }, placeholder: { searchPhrase: 'Rechercher des phrases…' }, empty: { noCategories: 'Aucune catégorie pour le moment', quickJump: 'Accéder à une catégorie', noResults: 'Aucun résultat', noPhrases: 'Aucune phrase pour le moment', noGroups: 'Aucun groupe pour le moment', uncategorized: 'Sans catégorie' },
  defaults: { groupName: 'Nouveau groupe', newGroup: 'Nouveau groupe', categoryName: 'Nouvelle catégorie', newCategory: 'Nouvelle catégorie', uncategorized: 'Sans catégorie', newPhrase: 'Nouvelle phrase', copySuffix: ' (copie)', iflytekGroupName: 'Depuis la méthode de saisie iFlytek', importGroupName: 'Données importées' },
  dialog: { unsavedChanges: 'Modifications non enregistrées', unsavedContent: 'Ce contenu n’a pas été enregistré. Enregistrer les modifications ?', unsavedContentNote: 'Les modifications non enregistrées seront perdues.', discard: 'Ignorer', thinkAgain: 'Poursuivre la modification', save: 'Enregistrer', exportTitle: 'Exporter une sauvegarde des phrases', exportIflytekTitle: 'Exporter pour la méthode de saisie iFlytek', importTitle: 'Importer une sauvegarde des phrases', jsonFilter: 'Fichiers JSON', csvFilter: 'Fichiers CSV', allSupportedFilter: 'Fichiers compatibles' },
  count: { categories: { one: '{count} catégorie', other: '{count} catégories' }, characters: { one: '{count} caractère', other: '{count} caractères' }, selected: { one: '{count} élément sélectionné', other: '{count} éléments sélectionnés' }, batchSelected: 'Sélection : {categories} catégories ; {phrases} phrases' }, section: { groups: 'Groupes de phrases' }, file: { backupName: 'sauvegarde-phrases-{date}.json', iflytekBackupName: 'sauvegarde-phrases-{date}.csv' },
  common: { cancel: 'Annuler', apply: 'Appliquer', close: 'Fermer', copy: 'Copier', listSeparator: ', ', groupSeparator: ' ; ', labelSeparator: ' : ' },
  settings: { title: 'Paramètres', language: 'Langue de l’interface', languageAuto: 'Automatique (langue du système)', themeMode: 'Thème', themeLight: 'Clair', themeDark: 'Sombre', themeAuto: 'Utiliser le réglage du système', startupSelection: 'Emplacement ouvert au démarrage', startupLast: 'Dernier emplacement consulté', startupFirst: 'Premier élément dans l’ordre', previewLinesLabel: 'Lignes d’aperçu des cartes', previewLines: 'Lignes d’aperçu des cartes : {count}', aiModel: 'Modèle d’IA', defaultAiModel: 'Modèle par défaut', aiPrompts: 'Instructions pour l’IA', aiCategorizePrompt: 'Instruction de classement', aiTitlePrompt: 'Instruction de titre', aiContentPrompt: 'Instruction de génération de contenu', updated: 'Mise à jour : {items}' },
  ai: {
    categorize: 'Classer avec l’IA', generateTitle: 'Générer le titre avec l’IA', generateContent: 'Générer du contenu avec l’IA', optimizeContent: 'Améliorer le contenu avec l’IA', themeGeneration: 'Générer à partir d’un thème', newGeneration: 'Créer un nouveau texte', optimizeExisting: 'Améliorer le texte actuel', useAsTheme: 'Utiliser comme thème', optimizeDescription: 'L’IA rendra le contenu actuel plus clair et plus professionnel.', extraRequirementsLabel: 'Consignes supplémentaires (facultatif)', descriptionLabel: 'Décrivez le contenu souhaité', extraRequirementsPlaceholder: 'Par exemple : adopter un ton plus formel et ajouter des remerciements…', descriptionPlaceholder: 'Par exemple : un e-mail pour refuser des heures supplémentaires ou un message de remerciement à un client…', contentApplied: 'Contenu appliqué', generating: 'Génération…', startOptimize: 'Améliorer', generate: 'Générer', inputRequired: 'Saisissez d’abord du contenu', titleGenerated: 'Titre généré', categorized: 'Classé dans {group} / {category}', categorizedCategory: 'Classé dans {category}', categoryNotFound: 'Catégorie introuvable : {category}', groupNotFound: 'Groupe introuvable : {group}', noSuggestion: 'L’IA n’a trouvé aucune catégorie adaptée', callFailed: 'Échec de la requête auprès de l’IA',
    prompt: { optimizeSystem: 'Vous êtes un réviseur professionnel. Améliorez le texte de l’utilisateur afin qu’il soit clair, naturel, professionnel et bien structuré, sans en changer le sens. Renvoyez uniquement le texte révisé, sans commentaire.', themeSystem: 'Vous êtes un assistant de rédaction professionnel. L’utilisateur fournira un texte existant comme thème. Rédigez une nouvelle phrase réutilisable, naturelle et professionnelle à partir de ce thème. Renvoyez uniquement le nouveau texte, sans commentaire.', themeUser: 'Thème :\n{content}\n\nRédigez un nouveau contenu à partir de ce thème.{extra}', extraRequirements: '\nConsignes supplémentaires : {prompt}', generateSystem: 'Vous êtes un assistant de rédaction professionnel. Rédigez une phrase réutilisable, concise, naturelle et professionnelle à partir de la description de l’utilisateur. Renvoyez uniquement le texte généré, sans commentaire.', categorizeSystem: 'Vous êtes un assistant de classement. Selon le contenu, choisissez la catégorie de premier niveau la plus adaptée et l’un de ses groupes dans la structure ci-dessous.\nStructure : {structure}\nRenvoyez uniquement du JSON au format exact suivant : {"分类":"nom de la catégorie","分组":"nom du groupe"}', titleSystem: 'Vous êtes un assistant de création de titres. Rédigez un titre court et précis pour le contenu, de 15 mots maximum. Renvoyez uniquement le titre.' }
  },
  accessibility: { copyPhrase: '{title}. Appuyez sur Entrée pour copier le contenu.' }, dynamic: { group: 'Groupe', category: 'Catégorie', phrase: 'Phrase', explain: 'Ouvrir ou copier une phrase' }, error: { emptyFile: 'Le fichier est vide', uncaught: 'Erreur non interceptée', unhandledPromise: 'Erreur asynchrone non gérée', renderTitle: 'Erreur de rendu React' },
  help: {
    sectionHierarchy: '📚 Organisation des données', hierarchyGroup: 'Groupe', hierarchyGroupDesc: 'Niveau supérieur', hierarchyCategory: 'Catégorie', hierarchyCategoryDesc: 'Dossier de classement', hierarchyPhrase: 'Phrase', hierarchyPhraseDesc: 'Contenu réutilisable',
    sectionFeatures: '✨ Fonctionnalités', featureCopyTitle: 'Copie en un clic', featureCopyDesc: 'Cliquez sur une carte pour copier son contenu dans le presse-papiers, prêt à être collé.', featureEditTitle: 'Modification rapide', featureEditDesc: 'Survolez une carte et appuyez sur {key} pour la modifier immédiatement.', featureDeleteTitle: 'Suppression et annulation', featureDeleteDesc: 'Pendant le survol, appuyez sur {delKey} pour supprimer ou sur {ctrlKey}+{zKey} pour annuler.', featureDragTitle: 'Déplacement par glisser-déposer', featureDragDesc: 'Faites glisser une carte vers la catégorie de destination. Maintenez {key} pendant le glissement pour la copier.', featureSearchTitle: 'Recherche globale', featureSearchDesc: 'Recherchez dans tous les groupes, puis cliquez sur un résultat pour y accéder directement.', featureBatchTitle: 'Sélection multiple', featureBatchDesc: 'Utilisez l’icône carrée à côté du champ de recherche pour sélectionner, supprimer, déplacer ou exporter plusieurs éléments.', featurePreviewTitle: 'Mode aperçu', featurePreviewDesc: 'Survolez une carte et appuyez une fois sur {key} pour activer ou désactiver le mode aperçu. Utilisez les flèches Haut et Bas pour changer de carte.', featureAutoSaveTitle: 'Enregistrement automatique', featureAutoSaveDesc: 'Après une modification, cliquez hors de l’éditeur ou changez de carte pour enregistrer automatiquement.', featureThemeTitle: 'Thème', featureThemeDesc: 'Ouvrez les Paramètres pour choisir un thème clair ou sombre, ou suivre le réglage du système.',
    sectionShortcuts: '⌨️ Raccourcis clavier', shortcutNewPhrase: 'Nouvelle phrase', shortcutNewCategory: 'Nouvelle catégorie', shortcutFocusSearch: 'Activer la recherche', shortcutForceSave: 'Enregistrer maintenant', shortcutUndo: 'Annuler', shortcutRedo: 'Rétablir', shortcutSelectAll: 'Tout sélectionner (sélection multiple)', shortcutClone: 'Dupliquer l’élément survolé', shortcutCopy: 'Copier l’élément survolé', shortcutEdit: 'Modifier l’élément survolé', shortcutDelete: 'Supprimer l’élément survolé', shortcutEscape: 'Quitter / Annuler', shortcutFullscreen: 'Éditeur plein écran', shortcutPreview: 'Activer ou désactiver l’aperçu', shortcutDragCopy: 'Copier vers la destination', dragAction: 'Glisser', startGuide: 'Démarrer le tutoriel'
  },
  guide: {
    steps: {
      step1Title: '🗂️ Groupes (niveau supérieur)', step1Message: 'Les groupes permettent de séparer les grands domaines de travail.\n\n• {bold:Créer} : cliquez sur le bouton {key:+} ci-dessus.\n• {bold:Changer} : cliquez sur un groupe pour afficher ses catégories.\n• {bold:Réorganiser} : maintenez un groupe et faites-le glisser vers la gauche ou la droite.\n• {bold:Plus} : faites un clic droit sur un groupe pour le {bold:renommer}, le {bold:supprimer} ou changer sa position.',
      step2Title: '📂 Catégories et menu contextuel', step2Message: 'Cette colonne affiche les catégories du groupe actuel.\n\n• {bold:Créer une catégorie} : ouvrez la liste déroulante des catégories, choisissez « Nouvelle catégorie… », saisissez un nom personnalisé, puis confirmez ; créez ou sélectionnez d’abord un groupe.\n• {bold:Menu contextuel} : faites un clic droit sur une catégorie pour la {bold:renommer}, la {bold:placer en haut} ou la {bold:supprimer}.\n• {bold:Renommage rapide} : sélectionnez une catégorie et appuyez sur {key:F2}.\n• {bold:Glisser-déposer} : faites glisser vers le haut ou le bas pour réorganiser, ou déposez la catégorie sur un autre groupe pour l’y déplacer.\n• {bold:Règles de nommage} : le nom ne peut pas être vide ; les doublons affichent un avertissement.',
      step3Title: '📝 Utilisation des phrases', step3Message: 'Voici votre espace de travail principal.\n\n• {bold:Copier} : cliquez sur une carte pour copier son contenu.\n• {bold:Raccourcis} :\n   - {key:Ctrl} + {key:C} copie\n   - {key:Ctrl} + {key:D} duplique\n   - {key:Suppr} supprime l’élément sélectionné\n• {bold:Réorganiser} : faites glisser les cartes vers le haut ou le bas.\n• {bold:Changer de catégorie} : déposez une carte sur une catégorie à gauche ; maintenez {key:Ctrl} pendant le glissement pour la copier.\n• {bold:Aperçu} : survolez une carte, appuyez une fois sur {key:Espace}, puis utilisez les flèches Haut et Bas.',
      step4Title: '🔍 Recherche et sélection multiple', step4Message: 'La barre d’outils supérieure donne accès à tout le contenu.\n\n• {bold:Recherche globale} ({key:Ctrl} + {key:F}) : recherchez dans tous les groupes et cliquez sur un résultat pour y accéder.\n• {bold:Sélection multiple} : cliquez sur l’icône carrée à droite.\n   - Maintenez {key:Maj} pour sélectionner une plage\n   - Utilisez la barre inférieure pour {bold:supprimer}, {bold:déplacer} ou {bold:exporter} les données sélectionnées.',
      step5Title: '⚙️ Sauvegardes et paramètres', step5Message: 'La barre d’outils inférieure rassemble les fonctions essentielles.\n\n• {bold:Importer / Exporter} : exportez régulièrement une sauvegarde JSON pour protéger vos données.\n• {bold:Paramètres} : choisissez la langue, le thème, l’emplacement de démarrage et le nombre de lignes d’aperçu.\n• {bold:Aide} : cliquez sur le point d’interrogation pour rouvrir ce tutoriel.'
    },
    controls: { skip: 'Ignorer', back: 'Retour', next: 'Suivant', finish: 'Terminer' },
    demo: { groupName: '✨ Groupe du tutoriel', categoryName: '📝 Catégorie d’exemple', phraseTitle: '👋 Bienvenue !', phraseContent: 'Voici une phrase d’exemple. Cliquez pour la copier ou essayez de la faire glisser.', phraseTitle2: '⌨️ Raccourcis clavier', phraseContent2: 'Sélectionnez-moi, puis appuyez sur Ctrl+C pour copier, Ctrl+D pour dupliquer ou Suppr pour supprimer.', phraseTitle3: '🖱️ Glisser et déplacer', phraseContent3: 'Maintenez et faites-moi glisser pour réorganiser, ou déposez-moi sur une autre catégorie à gauche.' }
  }
}
