// Hierarchy-specific copy is kept in one final locale layer so each language
// describes the same native model: category (top level) -> group -> phrase.
const createHierarchy = ({ category, group, phrase, categoryPlural, groupPlural, phrasePlural, newCategory, newGroup, noCategories, noGroups, uncategorized, categorized, categoryMissing, groupMissing, guide1, guide2, drag, search, importApplied, copy = {} }) => ({
  label: { category, group },
  dynamic: { category, group, phrase },
  menu: { newCategory: `${newCategory}…`, newGroup: `${newGroup}…` },
  tooltip: { newCategory, newGroup, moveToGroup: copy.moveToGroup || `Move to ${group}` },
  defaults: { categoryName: newCategory, newCategory, groupName: newGroup, newGroup, uncategorized },
  empty: { noCategories, noGroups, uncategorized, quickJump: `${category}: ${categoryPlural}` },
  section: { categories: categoryPlural, groups: groupPlural, phrases: phrasePlural },
  snackbar: {
    categoryRequired: copy.categoryRequired || `Select or create ${category} first`,
    ...(copy.categoryCreated ? { categoryCreated: copy.categoryCreated } : {}),
    ...(copy.categoryUpdated ? { categoryUpdated: copy.categoryUpdated } : {}),
    ...(copy.categoryDeleted ? { categoryDeleted: copy.categoryDeleted } : {}),
    ...(copy.categoryNameExists ? { categoryNameExists: copy.categoryNameExists } : {}),
    ...(copy.groupCreated ? { groupCreated: copy.groupCreated } : {}),
    ...(copy.groupUpdated ? { groupUpdated: copy.groupUpdated } : {}),
    ...(copy.groupDeleted ? { groupDeleted: copy.groupDeleted } : {}),
    ...(copy.groupNameExists ? { groupNameExists: copy.groupNameExists } : {}),
    batchMovedToCategory: copy.batchMovedToCategory || `Moved {groups} ${groupPlural} and {phrases} ${phrasePlural} to ${category}`,
    clonedToGroup: copy.clonedToGroup || `Copied to a new ${group}`, movedToGroup: copy.movedToGroup || `Moved to a new ${group}`,
    groupCopiedToCategory: copy.groupCopiedToCategory || `${group} copied to a new ${category}`,
    groupsCopiedToCategory: copy.groupsCopiedToCategory || { one: `{count} ${group} copied to a new ${category}`, other: `{count} ${groupPlural} copied to a new ${category}` },
    groupMovedToCategory: copy.groupMovedToCategory || `${group} moved to a new ${category}`,
    groupsMovedToCategory: copy.groupsMovedToCategory || { one: `{count} ${group} moved to a new ${category}`, other: `{count} ${groupPlural} moved to a new ${category}` },
    importApplied: copy.importApplied || importApplied,
    ...(copy.importSuccess ? { importSuccess: copy.importSuccess } : {}),
    ...(copy.batchExportSuccess ? { batchExportSuccess: copy.batchExportSuccess } : {}),
    ...(copy.iflytekImportSuccess ? { iflytekImportSuccess: copy.iflytekImportSuccess } : {}),
    ...(copy.createCategoryFirst ? { createCategoryFirst: copy.createCategoryFirst } : {})
  },
  count: { categories: { one: `{count} ${category}`, other: `{count} ${categoryPlural}` }, groups: { one: `{count} ${group}`, other: `{count} ${groupPlural}` }, batchSelected: copy.batchSelected || `Selected {groups} ${groupPlural} and {phrases} ${phrasePlural}` },
  importPreview: {
    categories: categoryPlural, groups: groupPlural, phrases: phrasePlural,
    mergeDescription: copy.mergeDescription || `Reuse matching ${categoryPlural} and their ${groupPlural}; identical ${phrasePlural} are skipped.`,
    copiesDescription: copy.copiesDescription || `Create independent imported ${categoryPlural} and retain every valid ${phrase} as a copy.`,
    overwriteDescription: copy.overwriteDescription || `Replace all ${categoryPlural}, ${groupPlural}, and ${phrasePlural} with the valid preview data.`
  },
  ai: {
    categorized: copy.categorized || categorized, categorizedCategory: copy.categorizedCategory || `${category}: {category}`, categoryNotFound: categoryMissing, groupNotFound: groupMissing, noSuggestion: copy.noSuggestion || `AI could not find a suitable ${category}`,
    prompt: copy.prompt || {}
  },
  help: {
    hierarchyCategory: category, hierarchyCategoryDesc: copy.hierarchyCategoryDesc || guide1, hierarchyGroup: group, hierarchyGroupDesc: copy.hierarchyGroupDesc || guide2, hierarchyPhrase: phrase, hierarchyPhraseDesc: copy.hierarchyPhraseDesc || phrase,
    featureDragDesc: copy.drag || drag, featureSearchDesc: copy.search || search,
    ...(copy.importJsonDesc ? { importJsonDesc: copy.importJsonDesc } : {})
  },
  guide: { steps: {
    step1Title: copy.step1Title || `🗂️ ${category} (${guide1})`, step1Message: copy.step1Message || `${category} is the top level. Create, rename, reorder, and switch ${categoryPlural} from the top bar. Each ${category} contains ${groupPlural}.`,
    step2Title: copy.step2Title || `📂 ${group} (${guide2})`, step2Message: copy.step2Message || `${groupPlural} belong to the current ${category}. Create a ${group} with a custom name, rename it, reorder it, or move it to another ${category}.`,
    step3Message: copy.step3Message || `${phrasePlural} belong to ${groupPlural}. Drag a card to another ${group} to move it; hold {key:Ctrl} while dragging to copy it.`,
    step4Message: copy.step4Message || `Search across every ${category}. In selection mode, move selected ${phrasePlural} to a ${group}, or move selected ${groupPlural} to a ${category}.`
  }, demo: {
    categoryName: copy.demoCategoryName || `Sample ${category}`,
    groupName: copy.demoGroupName || `Sample ${group}`,
    phraseContent3: copy.demoPhraseContent3 || `Press and drag me to reorder, or drop me on another ${group} on the left.`
  } }
})

// Every value below is intentionally complete for the hierarchy-sensitive UI.
const localizedCopy = {
  'zh-CN': { moveToGroup: '移动到分组', categoryRequired: '请先创建或选择一个分类', categoryCreated: '分类已创建', categoryUpdated: '分类已更新', categoryDeleted: '分类已删除', categoryNameExists: '分类名称已存在', groupCreated: '分组已创建', groupUpdated: '分组已更新', groupDeleted: '分组已删除', groupNameExists: '分组名称已存在', importSuccess: '导入了 {categories} 个分类，{phrases} 个常用语', batchExportSuccess: '已导出 {categories} 个分类，{phrases} 个常用语', iflytekImportSuccess: '从讯飞输入法导入了 {categories} 个分类，{phrases} 个常用语', createCategoryFirst: '请先创建分类', batchMovedToCategory: '已移动 {groups} 个分组、{phrases} 条常用语到分类', clonedToGroup: '已克隆到新分组', movedToGroup: '已移动到新分组', groupCopiedToCategory: '分组已复制到新分类', groupsCopiedToCategory: { one: '已复制 {count} 个分组到新分类', other: '已复制 {count} 个分组到新分类' }, groupMovedToCategory: '分组已移动到新分类', groupsMovedToCategory: { one: '已移动 {count} 个分组到新分类', other: '已移动 {count} 个分组到新分类' }, batchSelected: '已选 {groups} 个分组、{phrases} 条常用语', mergeDescription: '复用同名分类和分组，并跳过内容完全相同的常用语。', copiesDescription: '创建独立的导入分类，保留所有有效常用语副本。', overwriteDescription: '用预览中的有效数据替换当前全部分类、分组和常用语。', noSuggestion: 'AI 未能推荐合适的分类', step1Title: '🗂️ 分类（顶层）', step1Message: '分类用于管理不同的大类业务场景。可在顶部创建、重命名、排序并切换分类；每个分类包含多个分组。', step2Title: '📂 分组（子级）', step2Message: '分组属于当前分类。可使用自定义名称新建、重命名、排序分组，或将分组移动到其他分类。', step3Message: '常用语属于分组。将卡片拖到其他分组即可移动，按住 {key:Ctrl} 拖拽可复制。', step4Message: '搜索所有分类。批量模式下，可将选中的常用语移动到分组，或将选中的分组移动到分类。', demoCategoryName: '📝 示例分类', demoGroupName: '✨ 新手引导分组', demoPhraseContent3: '长按我可以进行排序，也可以将我拖到左侧的其他分组中。' },
  'zh-HK': { moveToGroup: '移動到群組', categoryRequired: '請先建立或選擇分類', batchMovedToCategory: '已將 {groups} 個群組、{phrases} 條常用語移動到分類', clonedToGroup: '已複製到新群組', movedToGroup: '已移動到新群組', groupCopiedToCategory: '群組已複製到新分類', groupsCopiedToCategory: { one: '已複製 {count} 個群組到新分類', other: '已複製 {count} 個群組到新分類' }, groupMovedToCategory: '群組已移動到新分類', groupsMovedToCategory: { one: '已移動 {count} 個群組到新分類', other: '已移動 {count} 個群組到新分類' }, batchSelected: '已選取 {groups} 個群組、{phrases} 條常用語', mergeDescription: '沿用同名分類和群組，並略過內容完全相同的常用語。', copiesDescription: '建立獨立的匯入分類，保留所有有效常用語複本。', overwriteDescription: '使用預覽中的有效資料取代目前所有分類、群組和常用語。', noSuggestion: 'AI 找不到合適的分類', step1Title: '🗂️ 分類（最上層）', step1Message: '分類用來管理不同的大型工作情境。你可在頂部建立、重新命名、排序及切換分類；每個分類包含多個群組。', step2Title: '📂 群組（子級）', step2Message: '群組屬於目前分類。可使用自訂名稱新增、重新命名、排序群組，或將群組移動到其他分類。', step3Message: '常用語屬於群組。將卡片拖到其他群組即可移動，按住 {key:Ctrl} 拖曳可複製。', step4Message: '搜尋所有分類。多選模式下，可將選取的常用語移動到群組，或將選取的群組移動到分類。', demoPhraseContent3: '長按我可以進行排序，也可以將我拖到左側的其他群組中。' },
  'zh-TW': { moveToGroup: '移動到群組', categoryRequired: '請先建立或選擇分類', batchMovedToCategory: '已將 {groups} 個群組、{phrases} 則常用語移動到分類', clonedToGroup: '已複製到新群組', movedToGroup: '已移動到新群組', groupCopiedToCategory: '群組已複製到新分類', groupsCopiedToCategory: { one: '已複製 {count} 個群組到新分類', other: '已複製 {count} 個群組到新分類' }, groupMovedToCategory: '群組已移動到新分類', groupsMovedToCategory: { one: '已移動 {count} 個群組到新分類', other: '已移動 {count} 個群組到新分類' }, batchSelected: '已選取 {groups} 個群組、{phrases} 則常用語', mergeDescription: '沿用同名分類與群組，並略過內容完全相同的常用語。', copiesDescription: '建立獨立的匯入分類，保留所有有效常用語副本。', overwriteDescription: '使用預覽中的有效資料取代目前全部分類、群組和常用語。', noSuggestion: 'AI 找不到合適的分類', step1Title: '🗂️ 分類（最上層）', step1Message: '分類用來管理不同的大型工作情境。你可在頂端建立、重新命名、排序及切換分類；每個分類包含多個群組。', step2Title: '📂 群組（子級）', step2Message: '群組屬於目前分類。可使用自訂名稱新增、重新命名、排序群組，或將群組移動到其他分類。', step3Message: '常用語屬於群組。將卡片拖到其他群組即可移動，按住 {key:Ctrl} 拖曳可複製。', step4Message: '搜尋所有分類。多選模式下，可將選取的常用語移動到群組，或將選取的群組移動到分類。', demoPhraseContent3: '長按我可以進行排序，也可以將我拖到左側的其他群組中。' },
  en: { moveToGroup: 'Move to group', categoryRequired: 'Select or create a category first', batchMovedToCategory: 'Moved {groups} groups and {phrases} phrases to the category', clonedToGroup: 'Copied to a new group', movedToGroup: 'Moved to a new group', groupCopiedToCategory: 'Group copied to a new category', groupsCopiedToCategory: { one: '{count} group copied to a new category', other: '{count} groups copied to a new category' }, groupMovedToCategory: 'Group moved to a new category', groupsMovedToCategory: { one: '{count} group moved to a new category', other: '{count} groups moved to a new category' }, batchSelected: 'Selected {groups} groups and {phrases} phrases', mergeDescription: 'Reuse categories and groups with matching names, and skip phrases with identical content.', copiesDescription: 'Create independent imported categories and keep every valid phrase as a copy.', overwriteDescription: 'Replace all current categories, groups, and phrases with the valid preview data.', noSuggestion: 'AI could not find a suitable category', step1Title: '🗂️ Categories (top level)', step1Message: 'Categories organize broad work areas. Create, rename, reorder, and switch categories from the top bar; each category contains groups.', step2Title: '📂 Groups (nested)', step2Message: 'Groups belong to the current category. Create a group with a custom name, rename or reorder it, or move it to another category.', step3Message: 'Phrases belong to groups. Drag a card to another group to move it; hold {key:Ctrl} while dragging to copy it.', step4Message: 'Search across every category. In selection mode, move selected phrases to a group or selected groups to a category.', demoPhraseContent3: 'Press and drag me to reorder, or drop me on another group on the left.' },
  ja: { moveToGroup: 'グループへ移動', categoryRequired: '先にカテゴリを作成または選択してください', batchMovedToCategory: '{groups}件のグループと{phrases}件の定型文をカテゴリへ移動しました', clonedToGroup: '新しいグループにコピーしました', movedToGroup: '新しいグループに移動しました', groupCopiedToCategory: 'グループを新しいカテゴリにコピーしました', groupsCopiedToCategory: { one: '{count}件のグループを新しいカテゴリにコピーしました', other: '{count}件のグループを新しいカテゴリにコピーしました' }, groupMovedToCategory: 'グループを新しいカテゴリに移動しました', groupsMovedToCategory: { one: '{count}件のグループを新しいカテゴリに移動しました', other: '{count}件のグループを新しいカテゴリに移動しました' }, batchSelected: 'グループ{groups}件、定型文{phrases}件を選択中', mergeDescription: '同名のカテゴリとグループを再利用し、内容が同じ定型文は除外します。', copiesDescription: '独立したインポートカテゴリを作成し、有効な定型文をすべてコピーとして保持します。', overwriteDescription: 'プレビューの有効なデータで現在のカテゴリ、グループ、定型文をすべて置き換えます。', noSuggestion: 'AIが適切なカテゴリを見つけられませんでした', step1Title: '🗂️ カテゴリ（最上位）', step1Message: 'カテゴリで大きな作業領域を整理します。上部から作成、名前変更、並べ替え、切り替えができ、各カテゴリに複数のグループがあります。', step2Title: '📂 グループ（子階層）', step2Message: 'グループは現在のカテゴリに属します。名前を指定して作成し、名前変更や並べ替え、別のカテゴリへの移動ができます。', step3Message: '定型文はグループに属します。カードを別のグループへドラッグして移動し、{key:Ctrl}を押しながらドラッグするとコピーします。', step4Message: 'すべてのカテゴリを検索できます。選択モードでは、定型文をグループへ、グループをカテゴリへ移動できます。', demoPhraseContent3: '長押しして並べ替えたり、左側の別のグループへドラッグしたりできます。' },
  vi: { moveToGroup: 'Chuyển đến nhóm', categoryRequired: 'Hãy tạo hoặc chọn một danh mục trước', batchMovedToCategory: 'Đã chuyển {groups} nhóm và {phrases} mẫu câu vào danh mục', clonedToGroup: 'Đã sao chép vào nhóm mới', movedToGroup: 'Đã chuyển vào nhóm mới', groupCopiedToCategory: 'Đã sao chép nhóm vào danh mục mới', groupsCopiedToCategory: { one: 'Đã sao chép {count} nhóm vào danh mục mới', other: 'Đã sao chép {count} nhóm vào danh mục mới' }, groupMovedToCategory: 'Đã chuyển nhóm vào danh mục mới', groupsMovedToCategory: { one: 'Đã chuyển {count} nhóm vào danh mục mới', other: 'Đã chuyển {count} nhóm vào danh mục mới' }, batchSelected: 'Đã chọn {groups} nhóm và {phrases} mẫu câu', mergeDescription: 'Dùng lại danh mục và nhóm trùng tên, đồng thời bỏ qua mẫu câu có nội dung giống hệt.', copiesDescription: 'Tạo danh mục nhập độc lập và giữ mọi mẫu câu hợp lệ dưới dạng bản sao.', overwriteDescription: 'Thay thế toàn bộ danh mục, nhóm và mẫu câu hiện tại bằng dữ liệu hợp lệ trong bản xem trước.', noSuggestion: 'AI không tìm được danh mục phù hợp', step1Title: '🗂️ Danh mục (cấp cao nhất)', step1Message: 'Danh mục giúp tổ chức các lĩnh vực công việc lớn. Bạn có thể tạo, đổi tên, sắp xếp và chuyển danh mục ở thanh trên; mỗi danh mục chứa các nhóm.', step2Title: '📂 Nhóm (cấp con)', step2Message: 'Nhóm thuộc danh mục hiện tại. Tạo nhóm với tên tùy chỉnh, đổi tên, sắp xếp hoặc chuyển nhóm sang danh mục khác.', step3Message: 'Mẫu câu thuộc các nhóm. Kéo thẻ sang nhóm khác để di chuyển; giữ {key:Ctrl} khi kéo để sao chép.', step4Message: 'Tìm kiếm trong mọi danh mục. Ở chế độ chọn, chuyển mẫu câu đã chọn vào nhóm hoặc nhóm đã chọn vào danh mục.', demoPhraseContent3: 'Nhấn và kéo tôi để sắp xếp, hoặc thả vào nhóm khác ở bên trái.' },
  ko: { moveToGroup: '그룹으로 이동', categoryRequired: '먼저 카테고리를 만들거나 선택하세요', batchMovedToCategory: '그룹 {groups}개와 상용구 {phrases}개를 카테고리로 이동했습니다', clonedToGroup: '새 그룹에 복사했습니다', movedToGroup: '새 그룹으로 이동했습니다', groupCopiedToCategory: '그룹을 새 카테고리에 복사했습니다', groupsCopiedToCategory: { one: '그룹 {count}개를 새 카테고리에 복사했습니다', other: '그룹 {count}개를 새 카테고리에 복사했습니다' }, groupMovedToCategory: '그룹을 새 카테고리로 이동했습니다', groupsMovedToCategory: { one: '그룹 {count}개를 새 카테고리로 이동했습니다', other: '그룹 {count}개를 새 카테고리로 이동했습니다' }, batchSelected: '그룹 {groups}개, 상용구 {phrases}개 선택됨', mergeDescription: '이름이 같은 카테고리와 그룹을 재사용하고 내용이 동일한 상용구는 건너뜁니다.', copiesDescription: '독립된 가져오기 카테고리를 만들고 유효한 상용구를 모두 사본으로 유지합니다.', overwriteDescription: '미리 보기의 유효한 데이터로 현재 모든 카테고리, 그룹, 상용구를 바꿉니다.', noSuggestion: 'AI가 알맞은 카테고리를 찾지 못했습니다', step1Title: '🗂️ 카테고리 (최상위)', step1Message: '카테고리로 큰 업무 영역을 정리합니다. 위쪽에서 만들기, 이름 변경, 정렬, 전환을 할 수 있으며 각 카테고리에 그룹이 포함됩니다.', step2Title: '📂 그룹 (하위)', step2Message: '그룹은 현재 카테고리에 속합니다. 사용자 지정 이름으로 만들고 이름 변경, 정렬 또는 다른 카테고리로 이동할 수 있습니다.', step3Message: '상용구는 그룹에 속합니다. 카드를 다른 그룹으로 끌어 이동하고 {key:Ctrl}을 누른 채 끌면 복사합니다.', step4Message: '모든 카테고리를 검색합니다. 선택 모드에서 상용구를 그룹으로, 그룹을 카테고리로 이동할 수 있습니다.', demoPhraseContent3: '길게 눌러 순서를 바꾸거나 왼쪽의 다른 그룹으로 끌어 놓으세요.' },
  es: { moveToGroup: 'Mover al grupo', categoryRequired: 'Crea o selecciona primero una categoría', batchMovedToCategory: 'Se han movido {groups} grupos y {phrases} frases a la categoría', clonedToGroup: 'Copiado a un grupo nuevo', movedToGroup: 'Movido a un grupo nuevo', groupCopiedToCategory: 'Grupo copiado a una categoría nueva', groupsCopiedToCategory: { one: '{count} grupo copiado a una categoría nueva', other: '{count} grupos copiados a una categoría nueva' }, groupMovedToCategory: 'Grupo movido a una categoría nueva', groupsMovedToCategory: { one: '{count} grupo movido a una categoría nueva', other: '{count} grupos movidos a una categoría nueva' }, batchSelected: 'Seleccionados {groups} grupos y {phrases} frases', mergeDescription: 'Reutiliza categorías y grupos con el mismo nombre y omite las frases con contenido idéntico.', copiesDescription: 'Crea categorías importadas independientes y conserva cada frase válida como copia.', overwriteDescription: 'Sustituye todas las categorías, grupos y frases actuales por los datos válidos de la vista previa.', noSuggestion: 'La IA no ha encontrado una categoría adecuada', step1Title: '🗂️ Categorías (nivel superior)', step1Message: 'Las categorías organizan grandes áreas de trabajo. Créelas, renómbralas, ordénalas y cámbialas desde la barra superior; cada categoría contiene grupos.', step2Title: '📂 Grupos (anidados)', step2Message: 'Los grupos pertenecen a la categoría actual. Crea un grupo con un nombre personalizado, renómbralo, ordénalo o muévelo a otra categoría.', step3Message: 'Las frases pertenecen a los grupos. Arrastra una tarjeta a otro grupo para moverla; mantén {key:Ctrl} al arrastrar para copiarla.', step4Message: 'Busca en todas las categorías. En modo de selección, mueve las frases seleccionadas a un grupo o los grupos seleccionados a una categoría.', demoPhraseContent3: 'Mantén pulsada y arrástrame para reordenar o suéltame en otro grupo de la izquierda.' },
  fr: { moveToGroup: 'Déplacer vers le groupe', categoryRequired: 'Créez ou sélectionnez d’abord une catégorie', batchMovedToCategory: '{groups} groupes et {phrases} phrases déplacés vers la catégorie', clonedToGroup: 'Copié dans un nouveau groupe', movedToGroup: 'Déplacé vers un nouveau groupe', groupCopiedToCategory: 'Groupe copié dans une nouvelle catégorie', groupsCopiedToCategory: { one: '{count} groupe copié dans une nouvelle catégorie', other: '{count} groupes copiés dans une nouvelle catégorie' }, groupMovedToCategory: 'Groupe déplacé vers une nouvelle catégorie', groupsMovedToCategory: { one: '{count} groupe déplacé vers une nouvelle catégorie', other: '{count} groupes déplacés vers une nouvelle catégorie' }, batchSelected: '{groups} groupes et {phrases} phrases sélectionnés', mergeDescription: 'Réutilise les catégories et groupes de même nom et ignore les phrases au contenu identique.', copiesDescription: 'Crée des catégories importées indépendantes et conserve chaque phrase valide comme copie.', overwriteDescription: 'Remplace toutes les catégories, tous les groupes et toutes les phrases par les données valides de l’aperçu.', noSuggestion: 'L’IA n’a trouvé aucune catégorie adaptée', step1Title: '🗂️ Catégories (niveau supérieur)', step1Message: 'Les catégories organisent les grands domaines de travail. Créez-les, renommez-les, réorganisez-les et changez de catégorie depuis la barre supérieure ; chaque catégorie contient des groupes.', step2Title: '📂 Groupes (imbriqués)', step2Message: 'Les groupes appartiennent à la catégorie actuelle. Créez un groupe avec un nom personnalisé, renommez-le, réorganisez-le ou déplacez-le vers une autre catégorie.', step3Message: 'Les phrases appartiennent aux groupes. Faites glisser une carte vers un autre groupe pour la déplacer ; maintenez {key:Ctrl} pour la copier.', step4Message: 'Recherchez dans toutes les catégories. En mode sélection, déplacez les phrases sélectionnées vers un groupe ou les groupes sélectionnés vers une catégorie.', demoPhraseContent3: 'Maintenez-moi et faites-moi glisser pour réorganiser, ou déposez-moi dans un autre groupe à gauche.' },
  'pt-BR': { moveToGroup: 'Mover para o grupo', categoryRequired: 'Crie ou selecione uma categoria primeiro', batchMovedToCategory: '{groups} grupos e {phrases} frases movidos para a categoria', clonedToGroup: 'Copiado para um novo grupo', movedToGroup: 'Movido para um novo grupo', groupCopiedToCategory: 'Grupo copiado para uma nova categoria', groupsCopiedToCategory: { one: '{count} grupo copiado para uma nova categoria', other: '{count} grupos copiados para uma nova categoria' }, groupMovedToCategory: 'Grupo movido para uma nova categoria', groupsMovedToCategory: { one: '{count} grupo movido para uma nova categoria', other: '{count} grupos movidos para uma nova categoria' }, batchSelected: '{groups} grupos e {phrases} frases selecionados', mergeDescription: 'Reutiliza categorias e grupos com o mesmo nome e ignora frases com conteúdo idêntico.', copiesDescription: 'Cria categorias importadas independentes e mantém cada frase válida como cópia.', overwriteDescription: 'Substitui todas as categorias, grupos e frases atuais pelos dados válidos da prévia.', noSuggestion: 'A IA não encontrou uma categoria adequada', step1Title: '🗂️ Categorias (nível superior)', step1Message: 'As categorias organizam grandes áreas de trabalho. Crie, renomeie, reordene e alterne categorias na barra superior; cada categoria contém grupos.', step2Title: '📂 Grupos (aninhados)', step2Message: 'Os grupos pertencem à categoria atual. Crie um grupo com nome personalizado, renomeie, reordene ou mova-o para outra categoria.', step3Message: 'As frases pertencem aos grupos. Arraste um cartão para outro grupo para movê-lo; mantenha {key:Ctrl} pressionada para copiar.', step4Message: 'Pesquise em todas as categorias. No modo de seleção, mova as frases selecionadas para um grupo ou os grupos selecionados para uma categoria.', demoPhraseContent3: 'Pressione e arraste para reordenar ou solte em outro grupo à esquerda.' },
  'pt-PT': { moveToGroup: 'Mover para o grupo', categoryRequired: 'Crie ou selecione primeiro uma categoria', batchMovedToCategory: '{groups} grupos e {phrases} frases movidos para a categoria', clonedToGroup: 'Copiado para um novo grupo', movedToGroup: 'Movido para um novo grupo', groupCopiedToCategory: 'Grupo copiado para uma nova categoria', groupsCopiedToCategory: { one: '{count} grupo copiado para uma nova categoria', other: '{count} grupos copiados para uma nova categoria' }, groupMovedToCategory: 'Grupo movido para uma nova categoria', groupsMovedToCategory: { one: '{count} grupo movido para uma nova categoria', other: '{count} grupos movidos para uma nova categoria' }, batchSelected: '{groups} grupos e {phrases} frases selecionados', mergeDescription: 'Reutiliza categorias e grupos com o mesmo nome e ignora frases com conteúdo idêntico.', copiesDescription: 'Cria categorias importadas independentes e mantém cada frase válida como cópia.', overwriteDescription: 'Substitui todas as categorias, grupos e frases atuais pelos dados válidos da pré-visualização.', noSuggestion: 'A IA não encontrou uma categoria adequada', step1Title: '🗂️ Categorias (nível superior)', step1Message: 'As categorias organizam grandes áreas de trabalho. Crie, mude o nome, reordene e alterne categorias na barra superior; cada categoria contém grupos.', step2Title: '📂 Grupos (aninhados)', step2Message: 'Os grupos pertencem à categoria atual. Crie um grupo com nome personalizado, mude o nome, reordene ou mova-o para outra categoria.', step3Message: 'As frases pertencem aos grupos. Arraste um cartão para outro grupo para o mover; mantenha {key:Ctrl} premida para copiar.', step4Message: 'Pesquise em todas as categorias. No modo de seleção, mova as frases selecionadas para um grupo ou os grupos selecionados para uma categoria.', demoPhraseContent3: 'Prima e arraste para reordenar ou largue noutro grupo à esquerda.' },
  ru: { moveToGroup: 'Переместить в группу', categoryRequired: 'Сначала создайте или выберите категорию', batchMovedToCategory: 'Перемещено в категорию: групп — {groups}, фраз — {phrases}', clonedToGroup: 'Скопировано в новую группу', movedToGroup: 'Перемещено в новую группу', groupCopiedToCategory: 'Группа скопирована в новую категорию', groupsCopiedToCategory: { one: '{count} группа скопирована в новую категорию', other: '{count} групп скопировано в новую категорию' }, groupMovedToCategory: 'Группа перемещена в новую категорию', groupsMovedToCategory: { one: '{count} группа перемещена в новую категорию', other: '{count} групп перемещено в новую категорию' }, batchSelected: 'Выбрано: групп — {groups}, фраз — {phrases}', mergeDescription: 'Использовать категории и группы с теми же названиями, а фразы с одинаковым содержимым пропустить.', copiesDescription: 'Создать отдельные категории импорта и сохранить каждую подходящую фразу как копию.', overwriteDescription: 'Заменить все текущие категории, группы и фразы действительными данными из предпросмотра.', noSuggestion: 'ИИ не смог подобрать подходящую категорию', step1Title: '🗂️ Категории (верхний уровень)', step1Message: 'Категории организуют крупные области работы. Создавайте, переименовывайте, меняйте порядок и переключайте категории на верхней панели; каждая категория содержит группы.', step2Title: '📂 Группы (вложенный уровень)', step2Message: 'Группы относятся к текущей категории. Создайте группу с собственным названием, переименуйте, измените порядок или переместите её в другую категорию.', step3Message: 'Фразы относятся к группам. Перетащите карточку в другую группу для перемещения; удерживайте {key:Ctrl}, чтобы скопировать её.', step4Message: 'Ищите во всех категориях. В режиме выбора перемещайте выбранные фразы в группу, а выбранные группы — в категорию.', demoPhraseContent3: 'Нажмите и перетащите меня для сортировки или перенесите в другую группу слева.' },
  de: { moveToGroup: 'In die Gruppe verschieben', categoryRequired: 'Erstellen oder wählen Sie zuerst eine Kategorie', batchMovedToCategory: '{groups} Gruppen und {phrases} Textbausteine in die Kategorie verschoben', clonedToGroup: 'In eine neue Gruppe kopiert', movedToGroup: 'In eine neue Gruppe verschoben', groupCopiedToCategory: 'Gruppe in eine neue Kategorie kopiert', groupsCopiedToCategory: { one: '{count} Gruppe in eine neue Kategorie kopiert', other: '{count} Gruppen in eine neue Kategorie kopiert' }, groupMovedToCategory: 'Gruppe in eine neue Kategorie verschoben', groupsMovedToCategory: { one: '{count} Gruppe in eine neue Kategorie verschoben', other: '{count} Gruppen in eine neue Kategorie verschoben' }, batchSelected: '{groups} Gruppen und {phrases} Textbausteine ausgewählt', mergeDescription: 'Gleichnamige Kategorien und Gruppen wiederverwenden und Textbausteine mit identischem Inhalt überspringen.', copiesDescription: 'Eigenständige Importkategorien erstellen und jeden gültigen Textbaustein als Kopie behalten.', overwriteDescription: 'Alle aktuellen Kategorien, Gruppen und Textbausteine durch die gültigen Vorschau-Daten ersetzen.', noSuggestion: 'Die KI konnte keine passende Kategorie finden', step1Title: '🗂️ Kategorien (oberste Ebene)', step1Message: 'Kategorien ordnen große Arbeitsbereiche. Sie können Kategorien oben erstellen, umbenennen, sortieren und wechseln; jede Kategorie enthält Gruppen.', step2Title: '📂 Gruppen (verschachtelt)', step2Message: 'Gruppen gehören zur aktuellen Kategorie. Erstellen Sie eine Gruppe mit eigenem Namen, benennen Sie sie um, sortieren Sie sie oder verschieben Sie sie in eine andere Kategorie.', step3Message: 'Textbausteine gehören zu Gruppen. Ziehen Sie eine Karte in eine andere Gruppe, um sie zu verschieben; halten Sie {key:Ctrl} gedrückt, um sie zu kopieren.', step4Message: 'Durchsuchen Sie alle Kategorien. Im Auswahlmodus können Sie ausgewählte Textbausteine in eine Gruppe und ausgewählte Gruppen in eine Kategorie verschieben.', demoPhraseContent3: 'Zum Sortieren gedrückt halten oder in eine andere Gruppe links ziehen.' },
  it: { moveToGroup: 'Sposta nel gruppo', categoryRequired: 'Crea o seleziona prima una categoria', batchMovedToCategory: '{groups} gruppi e {phrases} frasi spostati nella categoria', clonedToGroup: 'Copiato in un nuovo gruppo', movedToGroup: 'Spostato in un nuovo gruppo', groupCopiedToCategory: 'Gruppo copiato in una nuova categoria', groupsCopiedToCategory: { one: '{count} gruppo copiato in una nuova categoria', other: '{count} gruppi copiati in una nuova categoria' }, groupMovedToCategory: 'Gruppo spostato in una nuova categoria', groupsMovedToCategory: { one: '{count} gruppo spostato in una nuova categoria', other: '{count} gruppi spostati in una nuova categoria' }, batchSelected: '{groups} gruppi e {phrases} frasi selezionati', mergeDescription: 'Riutilizza categorie e gruppi con lo stesso nome e ignora le frasi con contenuto identico.', copiesDescription: 'Crea categorie importate indipendenti e conserva ogni frase valida come copia.', overwriteDescription: 'Sostituisce tutte le categorie, i gruppi e le frasi correnti con i dati validi dell’anteprima.', noSuggestion: 'L’IA non ha trovato una categoria adatta', step1Title: '🗂️ Categorie (livello superiore)', step1Message: 'Le categorie organizzano le grandi aree di lavoro. Creale, rinominale, riordinal e cambiale dalla barra superiore; ogni categoria contiene gruppi.', step2Title: '📂 Gruppi (annidati)', step2Message: 'I gruppi appartengono alla categoria corrente. Crea un gruppo con un nome personalizzato, rinominalo, riordinalo o spostalo in un’altra categoria.', step3Message: 'Le frasi appartengono ai gruppi. Trascina una scheda in un altro gruppo per spostarla; tieni premuto {key:Ctrl} per copiarla.', step4Message: 'Cerca in tutte le categorie. In modalità selezione puoi spostare le frasi selezionate in un gruppo o i gruppi selezionati in una categoria.', demoPhraseContent3: 'Tieni premuto e trascinami per riordinare oppure spostami in un altro gruppo a sinistra.' }
}

const entries = {
  'zh-CN': ['分类', '分组', '常用语', '分类', '分组', '常用语', '新建分类', '新建分组', '还没有分类', '还没有分组', '未分组', '已归类到：{category} / {group}', '未找到分类：{category}', '未找到分组：{group}', '顶层', '子级', '将卡片拖到目标分组；按住 {key} 拖动可复制。', '搜索所有分类，点击结果即可定位。', '已导入 {categories} 个分类、{groups} 个分组和 {phrases} 条常用语，跳过 {duplicates} 个重复项'],
  'zh-HK': ['分類', '群組', '常用語', '分類', '群組', '常用語', '新增分類', '新增群組', '尚未新增分類', '尚未新增群組', '未分組', '已分類到：{category} / {group}', '找不到分類：{category}', '找不到群組：{group}', '最上層', '子級', '將卡片拖到目標群組；按住 {key} 拖曳可複製。', '搜尋所有分類，點擊結果即可前往。', '已匯入 {categories} 個分類、{groups} 個群組及 {phrases} 條常用語，略過 {duplicates} 個重複項目'],
  'zh-TW': ['分類', '群組', '常用語', '分類', '群組', '常用語', '新增分類', '新增群組', '尚未建立分類', '尚未建立群組', '未分組', '已分類到：{category} / {group}', '找不到分類：{category}', '找不到群組：{group}', '最上層', '子級', '將卡片拖到目標群組；按住 {key} 拖曳可複製。', '搜尋所有分類，按一下結果即可前往。', '已匯入 {categories} 個分類、{groups} 個群組與 {phrases} 則常用語，略過 {duplicates} 個重複項目'],
  en: ['Category', 'Group', 'Phrase', 'Categories', 'Groups', 'Phrases', 'New category', 'New group', 'No categories yet', 'No groups yet', 'Ungrouped', 'Categorized under {category} / {group}', 'Category not found: {category}', 'Group not found: {group}', 'top level', 'nested', 'Drag a card to the target group. Hold {key} while dragging to copy it.', 'Search across every category, then click a result to jump to it.', 'Imported {categories} categories, {groups} groups, and {phrases} phrases; skipped {duplicates} duplicates'],
  ja: ['カテゴリ', 'グループ', '定型文', 'カテゴリ', 'グループ', '定型文', '新しいカテゴリ', '新しいグループ', 'カテゴリはまだありません', 'グループはまだありません', '未所属グループ', '{category} / {group} に分類しました', 'カテゴリが見つかりません: {category}', 'グループが見つかりません: {group}', '最上位', '子階層', 'カードを目的のグループへドラッグします。{key} を押しながらドラッグするとコピーします。', 'すべてのカテゴリを検索し、結果をクリックして移動します。', '{categories}件のカテゴリ、{groups}件のグループ、{phrases}件の定型文をインポートし、{duplicates}件の重複を除外しました'],
  vi: ['Danh mục', 'Nhóm', 'Mẫu câu', 'Danh mục', 'Nhóm', 'Mẫu câu', 'Danh mục mới', 'Nhóm mới', 'Chưa có danh mục', 'Chưa có nhóm', 'Chưa nhóm', 'Đã phân loại vào {category} / {group}', 'Không tìm thấy danh mục: {category}', 'Không tìm thấy nhóm: {group}', 'cấp cao nhất', 'cấp con', 'Kéo thẻ vào nhóm đích. Giữ {key} khi kéo để sao chép.', 'Tìm trong mọi danh mục rồi bấm kết quả để chuyển đến.', 'Đã nhập {categories} danh mục, {groups} nhóm và {phrases} mẫu câu; bỏ qua {duplicates} mục trùng lặp'],
  ko: ['카테고리', '그룹', '상용구', '카테고리', '그룹', '상용구', '새 카테고리', '새 그룹', '아직 카테고리가 없습니다', '아직 그룹이 없습니다', '그룹 없음', '{category} / {group}으로 분류했습니다', '카테고리를 찾을 수 없습니다: {category}', '그룹을 찾을 수 없습니다: {group}', '최상위', '하위', '카드를 대상 그룹으로 끌어 놓으세요. {key}를 누른 채 끌면 복사합니다.', '모든 카테고리를 검색하고 결과를 클릭해 이동합니다.', '카테고리 {categories}개, 그룹 {groups}개, 상용구 {phrases}개를 가져오고 중복 항목 {duplicates}개를 건너뛰었습니다'],
  es: ['Categoría', 'Grupo', 'Frase', 'Categorías', 'Grupos', 'Frases', 'Nueva categoría', 'Nuevo grupo', 'Todavía no hay categorías', 'Todavía no hay grupos', 'Sin grupo', 'Clasificado en {category} / {group}', 'No se encuentra la categoría: {category}', 'No se encuentra el grupo: {group}', 'nivel superior', 'anidado', 'Arrastra una tarjeta al grupo de destino. Mantén {key} al arrastrar para copiarla.', 'Busca en todas las categorías y haz clic en un resultado para ir a él.', 'Se han importado {categories} categorías, {groups} grupos y {phrases} frases; se han omitido {duplicates} duplicados'],
  fr: ['Catégorie', 'Groupe', 'Phrase', 'Catégories', 'Groupes', 'Phrases', 'Nouvelle catégorie', 'Nouveau groupe', 'Aucune catégorie pour le moment', 'Aucun groupe pour le moment', 'Sans groupe', 'Classé dans {category} / {group}', 'Catégorie introuvable : {category}', 'Groupe introuvable : {group}', 'niveau supérieur', 'imbriqué', 'Faites glisser une carte vers le groupe de destination. Maintenez {key} pour la copier.', 'Recherchez dans toutes les catégories, puis cliquez sur un résultat.', '{categories} catégories, {groups} groupes et {phrases} phrases importés ; {duplicates} doublons ignorés'],
  'pt-BR': ['Categoria', 'Grupo', 'Frase', 'Categorias', 'Grupos', 'Frases', 'Nova categoria', 'Novo grupo', 'Ainda não há categorias', 'Ainda não há grupos', 'Sem grupo', 'Classificado em {category} / {group}', 'Categoria não encontrada: {category}', 'Grupo não encontrado: {group}', 'nível superior', 'aninhado', 'Arraste um cartão para o grupo de destino. Mantenha {key} para copiar.', 'Pesquise em todas as categorias e clique em um resultado.', '{categories} categorias, {groups} grupos e {phrases} frases importados; {duplicates} itens duplicados ignorados'],
  'pt-PT': ['Categoria', 'Grupo', 'Frase', 'Categorias', 'Grupos', 'Frases', 'Nova categoria', 'Novo grupo', 'Ainda não há categorias', 'Ainda não há grupos', 'Sem grupo', 'Classificado em {category} / {group}', 'Categoria não encontrada: {category}', 'Grupo não encontrado: {group}', 'nível superior', 'aninhado', 'Arraste um cartão para o grupo de destino. Mantenha {key} para copiar.', 'Pesquise em todas as categorias e clique num resultado.', '{categories} categorias, {groups} grupos e {phrases} frases importados; {duplicates} duplicados ignorados'],
  ru: ['Категория', 'Группа', 'Фраза', 'Категории', 'Группы', 'Фразы', 'Новая категория', 'Новая группа', 'Категорий пока нет', 'Групп пока нет', 'Без группы', 'Классифицировано: {category} / {group}', 'Категория не найдена: {category}', 'Группа не найдена: {group}', 'верхний уровень', 'вложенный', 'Перетащите карточку в целевую группу. Удерживайте {key}, чтобы скопировать.', 'Ищите во всех категориях и щёлкните результат для перехода.', 'Импортировано: категорий — {categories}, групп — {groups}, фраз — {phrases}; пропущено дубликатов: {duplicates}'],
  de: ['Kategorie', 'Gruppe', 'Textbaustein', 'Kategorien', 'Gruppen', 'Textbausteine', 'Neue Kategorie', 'Neue Gruppe', 'Noch keine Kategorien', 'Noch keine Gruppen', 'Ohne Gruppe', 'Einsortiert unter {category} / {group}', 'Kategorie nicht gefunden: {category}', 'Gruppe nicht gefunden: {group}', 'oberste Ebene', 'verschachtelt', 'Ziehe eine Karte in die Zielgruppe. Halte {key}, um sie zu kopieren.', 'Suche in allen Kategorien und klicke ein Ergebnis an.', '{categories} Kategorien, {groups} Gruppen und {phrases} Textbausteine importiert; {duplicates} Duplikate übersprungen'],
  it: ['Categoria', 'Gruppo', 'Frase', 'Categorie', 'Gruppi', 'Frasi', 'Nuova categoria', 'Nuovo gruppo', 'Non ci sono ancora categorie', 'Non ci sono ancora gruppi', 'Senza gruppo', 'Classificato in {category} / {group}', 'Categoria non trovata: {category}', 'Gruppo non trovato: {group}', 'livello superiore', 'annidato', 'Trascina una scheda nel gruppo di destinazione. Tieni premuto {key} per copiarla.', 'Cerca in tutte le categorie e fai clic su un risultato.', 'Importati {categories} categorie, {groups} gruppi e {phrases} frasi; ignorati {duplicates} duplicati']
}

export default Object.fromEntries(Object.entries(entries).map(([code, values]) => {
  const [category, group, phrase, categoryPlural, groupPlural, phrasePlural, newCategory, newGroup, noCategories, noGroups, uncategorized, categorized, categoryMissing, groupMissing, guide1, guide2, drag, search, importApplied] = values
  const localized = localizedCopy[code] || {}
  return [code, createHierarchy({ category, group, phrase, categoryPlural, groupPlural, phrasePlural, newCategory, newGroup, noCategories, noGroups, uncategorized, categorized, categoryMissing, groupMissing, guide1, guide2, drag, search, importApplied, copy: localized })]
}))
