export default {
  app: { title: 'Gestore di frasi' },
  snackbar: {
    selectParentCategoryFirst: 'Seleziona prima un gruppo', categoryDeleted: 'Categoria eliminata', categoryNameExists: 'Esiste già una categoria con questo nome', categoryCreated: 'Categoria creata', categoryUpdated: 'Categoria aggiornata', groupNameExists: 'Esiste già un gruppo con questo nome', groupCreated: 'Gruppo creato', groupUpdated: 'Gruppo aggiornato', groupDeleted: 'Gruppo eliminato', noGroup: 'Crea o seleziona prima un gruppo', undone: 'Azione annullata', redone: 'Azione ripetuta',
    noChanges: 'Nessuna modifica da salvare', duplicatePhrase: 'Esiste già una frase identica', phraseCreated: 'Frase creata', phraseUpdated: 'Modifiche salvate', phraseDeleted: 'Frase eliminata', titleEmpty: 'Il titolo non può essere vuoto', contentEmpty: 'Il contenuto è vuoto', saveFailed: 'Salvataggio non riuscito. Riprova.', copiedToClipboard: 'Copiato negli appunti', createCategoryFirst: 'Crea prima una categoria', itemsDeleted: { one: '{count} elemento eliminato', other: '{count} elementi eliminati' }, phrasesMoved: { one: '{count} frase spostata', other: '{count} frasi spostate' }, movedToTop: 'Spostato all’inizio', movedToBottom: 'Spostato alla fine', batchMovedToTop: 'Elementi selezionati spostati all’inizio', batchMovedToBottom: 'Elementi selezionati spostati alla fine', phraseCloned: 'Frase duplicata', clonedToCategory: 'Copiato nella nuova categoria', movedToCategory: 'Spostato nella nuova categoria',
    categoryCopiedToGroup: 'Categoria copiata nel nuovo gruppo', categoryMovedToGroup: 'Categoria spostata nel nuovo gruppo', categoriesCopiedToGroup: { one: '{count} categoria copiata nel nuovo gruppo', other: '{count} categorie copiate nel nuovo gruppo' }, categoriesMovedToGroup: { one: '{count} categoria spostata nel nuovo gruppo', other: '{count} categorie spostate nel nuovo gruppo' }, copiedToUncategorized: 'Copiato in “Senza categoria”', movedToUncategorized: 'Spostato in “Senza categoria”', phrasesCopiedToUncategorized: { one: '{count} frase copiata in “Senza categoria”', other: '{count} frasi copiate in “Senza categoria”' }, phrasesMovedToUncategorized: { one: '{count} frase spostata in “Senza categoria”', other: '{count} frasi spostate in “Senza categoria”' },
    exportSuccess: 'Esportazione completata', exportFailed: 'Esportazione non riuscita: {error}', importSuccess: 'Importazione completata. Categorie: {categories}; frasi: {phrases}', importFailed: 'Importazione non riuscita: {error}', batchExportSuccess: 'Esportazione completata. Categorie: {categories}; frasi: {phrases}', iflytekImportSuccess: 'Importazione dal metodo di input iFlytek completata. Categorie: {categories}; frasi: {phrases}', iflytekExportSuccess: 'Esportato nel formato del metodo di input iFlytek', batchMovedToGroup: 'Spostato nel gruppo. Categorie: {categories}; frasi: {phrases}', guideCompleted: 'Tutorial completato! Abbiamo aggiunto alcuni dati di esempio per permetterti di esplorare l’app.', cloudUpdatedDraftPreserved: 'I dati nel cloud sono stati aggiornati. La bozza corrente non è stata sovrascritta.'
  },
  tooltip: { newCategory: 'Nuova categoria (Ctrl+Maiusc+N)', newPhrase: 'Nuova frase (Ctrl+N)', help: 'Aiuto', switchToLight: 'Tema chiaro', switchToDark: 'Tema scuro', import: 'Importa', export: 'Esporta', sort: 'Ordina', batchMode: 'Selezione multipla', selectAll: 'Seleziona tutto / Deseleziona', moveToCategory: 'Sposta in una categoria', moveToTop: 'Sposta all’inizio', moveToBottom: 'Sposta alla fine', delete: 'Elimina', exit: 'Esci', clone: 'Duplica', edit: 'Modifica', newGroup: 'Nuovo gruppo', fullscreen: 'Editor a schermo intero', exitFullscreen: 'Esci da schermo intero', exitEdit: 'Chiudi editor', settings: 'Impostazioni' },
  menu: { rename: 'Rinomina', moveToTop: 'Sposta all’inizio', moveToBottom: 'Sposta alla fine', delete: 'Elimina', copyContent: 'Copia contenuto', clone: 'Duplica', edit: 'Modifica', sortCustom: 'Ordine personalizzato', sortUsageDesc: 'Più usate per prime', sortUsageAsc: 'Meno usate per prime', sortCreatedDesc: 'Più recenti per prime', sortCreatedAsc: 'Meno recenti per prime', sortUpdatedDesc: 'Modificate di recente per prime', sortUpdatedAsc: 'Modificate meno di recente per prime', sortTitleAsc: 'Titolo (A–Z)', sortTitleDesc: 'Titolo (Z–A)', newGroup: 'Nuovo gruppo…', newCategory: 'Nuova categoria…', exportNative: 'Esporta come JSON', exportIflytek: 'Esporta per il metodo di input iFlytek' },
  label: { group: 'Gruppo', category: 'Categoria', title: 'Titolo', content: 'Contenuto' }, placeholder: { searchPhrase: 'Cerca frasi…' }, empty: { noCategories: 'Non ci sono ancora categorie', quickJump: 'Vai a una categoria', noResults: 'Nessun risultato', noPhrases: 'Non ci sono ancora frasi', noGroups: 'Non ci sono ancora gruppi', uncategorized: 'Senza categoria' },
  defaults: { groupName: 'Nuovo gruppo', newGroup: 'Nuovo gruppo', categoryName: 'Nuova categoria', newCategory: 'Nuova categoria', uncategorized: 'Senza categoria', newPhrase: 'Nuova frase', copySuffix: ' (copia)', iflytekGroupName: 'Dal metodo di input iFlytek', importGroupName: 'Dati importati' },
  dialog: { unsavedChanges: 'Modifiche non salvate', unsavedContent: 'Questo contenuto non è stato salvato. Vuoi salvare le modifiche?', unsavedContentNote: 'Le modifiche non salvate andranno perse.', discard: 'Non salvare', thinkAgain: 'Continua a modificare', save: 'Salva', exportTitle: 'Esporta backup delle frasi', exportIflytekTitle: 'Esporta per il metodo di input iFlytek', importTitle: 'Importa backup delle frasi', jsonFilter: 'File JSON', csvFilter: 'File CSV', allSupportedFilter: 'File supportati' },
  count: { categories: { one: '{count} categoria', other: '{count} categorie' }, characters: { one: '{count} carattere', other: '{count} caratteri' }, selected: { one: '{count} elemento selezionato', other: '{count} elementi selezionati' }, batchSelected: 'Selezione — categorie: {categories}; frasi: {phrases}' }, section: { groups: 'Gruppi di frasi' }, file: { backupName: 'backup-frasi-{date}.json', iflytekBackupName: 'backup-frasi-{date}.csv' },
  common: { cancel: 'Annulla', apply: 'Applica', close: 'Chiudi', copy: 'Copia', listSeparator: ', ', groupSeparator: '; ', labelSeparator: ': ' },
  settings: { title: 'Impostazioni', language: 'Lingua dell’interfaccia', languageAuto: 'Automatica (lingua di sistema)', themeMode: 'Tema', themeLight: 'Chiaro', themeDark: 'Scuro', themeAuto: 'Usa impostazione di sistema', startupSelection: 'Apri all’avvio', startupLast: 'Ultima posizione visualizzata', startupFirst: 'Primo elemento nell’ordine', previewLinesLabel: 'Righe di anteprima delle schede', previewLines: 'Righe di anteprima: {count}', aiModel: 'Modello IA', defaultAiModel: 'Modello predefinito', aiPrompts: 'Istruzioni per l’IA', aiCategorizePrompt: 'Istruzioni per la categorizzazione', aiTitlePrompt: 'Istruzioni per il titolo', aiContentPrompt: 'Istruzioni per generare il contenuto', updated: 'Aggiornamento completato: {items}' },
  ai: {
    categorize: 'Classifica con l’IA', generateTitle: 'Genera titolo con l’IA', generateContent: 'Genera contenuto con l’IA', optimizeContent: 'Migliora contenuto con l’IA', themeGeneration: 'Genera da un tema', newGeneration: 'Crea da zero', optimizeExisting: 'Migliora il testo esistente', useAsTheme: 'Usa come tema', optimizeDescription: 'L’IA renderà il contenuto esistente più chiaro e professionale.', extraRequirementsLabel: 'Indicazioni aggiuntive (facoltative)', descriptionLabel: 'Descrivi il contenuto che ti serve', extraRequirementsPlaceholder: 'Ad esempio: usa un tono più formale e aggiungi un ringraziamento…', descriptionPlaceholder: 'Ad esempio: un’e-mail per rifiutare gli straordinari o un messaggio di ringraziamento a un cliente…', contentApplied: 'Contenuto applicato', generating: 'Generazione…', startOptimize: 'Migliora', generate: 'Genera', inputRequired: 'Inserisci prima del contenuto', titleGenerated: 'Titolo generato', categorized: 'Classificato in {group} / {category}', categorizedCategory: 'Classificato in {category}', categoryNotFound: 'Categoria non trovata: {category}', groupNotFound: 'Gruppo non trovato: {group}', noSuggestion: 'L’IA non ha trovato una categoria adatta', callFailed: 'Richiesta all’IA non riuscita',
    prompt: { optimizeSystem: 'Sei un revisore professionista. Migliora il testo dell’utente affinché sia chiaro, naturale, professionale e ben strutturato, senza alterarne il significato. Restituisci solo il testo rivisto, senza commenti.', themeSystem: 'Sei un assistente di scrittura professionale. L’utente fornirà un testo esistente come tema. Scrivi una nuova frase riutilizzabile, naturale e professionale basata su quel tema. Restituisci solo il nuovo testo, senza commenti.', themeUser: 'Tema:\n{content}\n\nScrivi un nuovo contenuto basato su questo tema.{extra}', extraRequirements: '\nIndicazioni aggiuntive: {prompt}', generateSystem: 'Sei un assistente di scrittura professionale. Scrivi una frase riutilizzabile concisa, naturale e professionale basata sulla descrizione dell’utente. Restituisci solo il testo generato, senza commenti.', categorizeSystem: 'Sei un assistente alla classificazione. In base al contenuto, scegli la categoria più adatta dalla struttura di gruppi e categorie seguente.\nStruttura: {structure}\nRestituisci solo JSON in questo formato esatto: {"分组":"nome del gruppo","分类":"nome della categoria"}', titleSystem: 'Sei un assistente per la creazione di titoli. Scrivi un titolo breve e preciso per il contenuto, di non più di 15 parole. Restituisci solo il titolo.' }
  },
  accessibility: { copyPhrase: '{title}. Premi Invio per copiare il contenuto.' }, dynamic: { group: 'Gruppo', category: 'Categoria', phrase: 'Frase', explain: 'Apri o copia una frase' }, error: { emptyFile: 'Il file è vuoto', uncaught: 'Errore non rilevato', unhandledPromise: 'Errore asincrono non gestito', renderTitle: 'Errore di rendering React' },
  help: {
    sectionHierarchy: '📚 Organizzazione dei dati', hierarchyGroup: 'Gruppo', hierarchyGroupDesc: 'Livello principale', hierarchyCategory: 'Categoria', hierarchyCategoryDesc: 'Cartella organizzativa', hierarchyPhrase: 'Frase', hierarchyPhraseDesc: 'Contenuto riutilizzabile',
    sectionFeatures: '✨ Funzioni', featureCopyTitle: 'Copia con un clic', featureCopyDesc: 'Fai clic su una scheda per copiarne il contenuto negli appunti, pronto da incollare.', featureEditTitle: 'Modifica rapida', featureEditDesc: 'Posiziona il puntatore su una scheda e premi {key} per modificarla subito.', featureDeleteTitle: 'Elimina e annulla', featureDeleteDesc: 'Con il puntatore sulla scheda, premi {delKey} per eliminare o {ctrlKey}+{zKey} per annullare.', featureDragTitle: 'Trascina per spostare', featureDragDesc: 'Trascina una scheda nella categoria di destinazione. Tieni premuto {key} mentre trascini per copiarla.', featureSearchTitle: 'Cerca ovunque', featureSearchDesc: 'Cerca in tutti i gruppi e fai clic su un risultato per raggiungerlo direttamente.', featureBatchTitle: 'Selezione multipla', featureBatchDesc: 'Usa l’icona quadrata accanto alla ricerca per selezionare, eliminare, spostare o esportare più elementi.', featurePreviewTitle: 'Modalità anteprima', featurePreviewDesc: 'Posiziona il puntatore su una scheda e premi {key} una volta per attivare o disattivare l’anteprima. Usa le frecce Su e Giù per cambiare scheda.', featureAutoSaveTitle: 'Salvataggio automatico', featureAutoSaveDesc: 'Dopo la modifica, fai clic fuori dall’editor o cambia scheda per salvare automaticamente.', featureThemeTitle: 'Tema', featureThemeDesc: 'Apri le Impostazioni per scegliere un tema chiaro o scuro oppure seguire il sistema.',
    sectionShortcuts: '⌨️ Scorciatoie da tastiera', shortcutNewPhrase: 'Nuova frase', shortcutNewCategory: 'Nuova categoria', shortcutFocusSearch: 'Attiva ricerca', shortcutForceSave: 'Salva ora', shortcutUndo: 'Annulla', shortcutRedo: 'Ripeti', shortcutSelectAll: 'Seleziona tutto (selezione multipla)', shortcutClone: 'Duplica l’elemento puntato', shortcutCopy: 'Copia l’elemento puntato', shortcutEdit: 'Modifica l’elemento puntato', shortcutDelete: 'Elimina l’elemento puntato', shortcutEscape: 'Esci / Annulla', shortcutFullscreen: 'Editor a schermo intero', shortcutPreview: 'Attiva/disattiva anteprima', shortcutDragCopy: 'Copia nella destinazione', dragAction: 'Trascina', startGuide: 'Avvia tutorial'
  },
  guide: {
    steps: {
      step1Title: '🗂️ Gruppi (livello principale)', step1Message: 'I gruppi separano le grandi aree di lavoro.\n\n• {bold:Crea}: fai clic sul pulsante {key:+} in alto.\n• {bold:Cambia}: fai clic su un gruppo per mostrarne le categorie.\n• {bold:Riordina}: tieni premuto un gruppo e trascinalo a sinistra o a destra.\n• {bold:Altro}: fai clic con il tasto destro su un gruppo per {bold:rinominarlo}, {bold:eliminarlo} o cambiarne la posizione.',
      step2Title: '📂 Categorie e menu contestuale', step2Message: 'Questa colonna mostra le categorie del gruppo corrente.\n\n• {bold:Crea una categoria}: apri l’elenco delle categorie, scegli «Nuova categoria…», inserisci un nome personalizzato e conferma; prima crea o seleziona un gruppo.\n• {bold:Menu contestuale}: fai clic con il tasto destro su una categoria per {bold:rinominarla}, {bold:spostarla all’inizio} o {bold:eliminarla}.\n• {bold:Rinomina rapida}: seleziona una categoria e premi {key:F2}.\n• {bold:Trascina e rilascia}: trascina in alto o in basso per riordinare oppure rilascia la categoria su un altro gruppo per spostarla.\n• {bold:Regole dei nomi}: il nome non può essere vuoto; i duplicati mostrano un avviso.',
      step3Title: '📝 Lavorare con le frasi', step3Message: 'Questa è l’area di lavoro principale.\n\n• {bold:Copia}: fai clic su una scheda per copiarne il contenuto.\n• {bold:Scorciatoie}:\n   - {key:Ctrl} + {key:C} copia\n   - {key:Ctrl} + {key:D} duplica\n   - {key:Canc} elimina l’elemento selezionato\n• {bold:Riordina}: trascina le schede in alto o in basso.\n• {bold:Sposta tra categorie}: rilascia una scheda su una categoria a sinistra; tieni premuto {key:Ctrl} mentre trascini per copiarla.\n• {bold:Anteprima}: posiziona il puntatore su una scheda, premi {key:Spazio} una volta e usa le frecce Su e Giù.',
      step4Title: '🔍 Ricerca e selezione multipla', step4Message: 'La barra superiore consente di accedere a tutti i contenuti.\n\n• {bold:Ricerca globale} ({key:Ctrl} + {key:F}): cerca in tutti i gruppi e fai clic su un risultato per raggiungerlo.\n• {bold:Selezione multipla}: fai clic sull’icona quadrata a destra.\n   - Tieni premuto {key:Maiusc} per selezionare un intervallo\n   - Usa la barra inferiore per {bold:eliminare}, {bold:spostare} o {bold:esportare} i dati selezionati.',
      step5Title: '⚙️ Backup e impostazioni', step5Message: 'La barra inferiore mantiene a portata di mano gli strumenti essenziali.\n\n• {bold:Importa / Esporta}: esporta regolarmente un backup JSON per proteggere i dati.\n• {bold:Impostazioni}: scegli lingua, tema, posizione iniziale e righe di anteprima.\n• {bold:Aiuto}: fai clic sul punto interrogativo per riaprire questo tutorial.'
    },
    controls: { skip: 'Salta', back: 'Indietro', next: 'Avanti', finish: 'Fine' },
    demo: { groupName: '✨ Gruppo del tutorial', categoryName: '📝 Categoria di esempio', phraseTitle: '👋 Benvenuto!', phraseContent: 'Questa è una frase di esempio. Fai clic per copiarla o prova a trascinarla.', phraseTitle2: '⌨️ Scorciatoie da tastiera', phraseContent2: 'Selezionami e premi Ctrl+C per copiare, Ctrl+D per duplicare o Canc per eliminare.', phraseTitle3: '🖱️ Trascina e sposta', phraseContent3: 'Tieni premuto e trascinami per riordinare, oppure rilasciami su un’altra categoria a sinistra.' }
  }
}
