export default {
  app: { title: '定型文管理' },
  snackbar: {
    selectParentCategoryFirst: '先にグループを選択してください', categoryDeleted: 'カテゴリを削除しました', categoryNameExists: '同じ名前のカテゴリが既にあります', categoryCreated: 'カテゴリを作成しました', categoryUpdated: 'カテゴリを更新しました', groupNameExists: '同じ名前のグループが既にあります', groupCreated: 'グループを作成しました', groupUpdated: 'グループを更新しました', groupDeleted: 'グループを削除しました', noGroup: '先にグループを作成または選択してください', undone: '操作を元に戻しました', redone: '操作をやり直しました',
    noChanges: '変更はありません', duplicatePhrase: '同じ定型文が既にあります', phraseCreated: '定型文を作成しました', phraseUpdated: '変更を保存しました', phraseDeleted: '定型文を削除しました', titleEmpty: 'タイトルを入力してください', contentEmpty: '内容が空です', saveFailed: '保存できませんでした。もう一度お試しください。', copiedToClipboard: 'クリップボードにコピーしました', createCategoryFirst: '先にカテゴリを作成してください',
    itemsDeleted: '{count}件を削除しました', phrasesMoved: '定型文を{count}件移動しました', movedToTop: '先頭へ移動しました', movedToBottom: '末尾へ移動しました', batchMovedToTop: '選択項目を先頭へ移動しました', batchMovedToBottom: '選択項目を末尾へ移動しました', phraseCloned: '定型文を複製しました', clonedToCategory: '新しいカテゴリへコピーしました', movedToCategory: '新しいカテゴリへ移動しました',
    categoryCopiedToGroup: 'カテゴリを新しいグループへコピーしました', categoryMovedToGroup: 'カテゴリを新しいグループへ移動しました', categoriesCopiedToGroup: 'カテゴリを{count}件、新しいグループへコピーしました', categoriesMovedToGroup: 'カテゴリを{count}件、新しいグループへ移動しました', copiedToUncategorized: '「未分類」へコピーしました', movedToUncategorized: '「未分類」へ移動しました', phrasesCopiedToUncategorized: '定型文を{count}件「未分類」へコピーしました', phrasesMovedToUncategorized: '定型文を{count}件「未分類」へ移動しました',
    exportSuccess: 'エクスポートが完了しました', exportFailed: 'エクスポートに失敗しました：{error}', importSuccess: 'カテゴリ{categories}件、定型文{phrases}件をインポートしました', importFailed: 'インポートに失敗しました：{error}', batchExportSuccess: 'カテゴリ{categories}件、定型文{phrases}件をエクスポートしました', iflytekImportSuccess: 'iFlytek入力メソッドからカテゴリ{categories}件、定型文{phrases}件をインポートしました', iflytekExportSuccess: 'iFlytek入力メソッド形式でエクスポートしました', batchMovedToGroup: 'カテゴリ{categories}件、定型文{phrases}件をグループへ移動しました', guideCompleted: 'チュートリアルは完了です。サンプルデータを用意したので、自由にお試しください。', cloudUpdatedDraftPreserved: 'クラウドのデータが更新されました。編集中の内容は上書きされていません。'
  },
  tooltip: { newCategory: '新しいカテゴリ (Ctrl+Shift+N)', newPhrase: '新しい定型文 (Ctrl+N)', help: 'ヘルプ', switchToLight: 'ライトテーマ', switchToDark: 'ダークテーマ', import: 'インポート', export: 'エクスポート', sort: '並べ替え', batchMode: '複数選択', selectAll: 'すべて選択／選択解除', moveToCategory: 'カテゴリへ移動', moveToTop: '先頭へ移動', moveToBottom: '末尾へ移動', delete: '削除', exit: '終了', clone: '複製', edit: '編集', newGroup: '新しいグループ', fullscreen: '全画面で編集', exitFullscreen: '全画面表示を終了', exitEdit: '編集を終了', settings: '設定' },
  menu: { rename: '名前を変更', moveToTop: '先頭へ移動', moveToBottom: '末尾へ移動', delete: '削除', copyContent: '内容をコピー', clone: '複製', edit: '編集', sortCustom: '手動で並べ替え', sortUsageDesc: '使用回数（多い順）', sortUsageAsc: '使用回数（少ない順）', sortCreatedDesc: '作成日時（新しい順）', sortCreatedAsc: '作成日時（古い順）', sortUpdatedDesc: '更新日時（新しい順）', sortUpdatedAsc: '更新日時（古い順）', sortTitleAsc: 'タイトル（A–Z）', sortTitleDesc: 'タイトル（Z–A）', newGroup: '新しいグループ…', newCategory: '新しいカテゴリ…', exportNative: 'JSONでエクスポート', exportIflytek: 'iFlytek形式でエクスポート' },
  label: { group: 'グループ', category: 'カテゴリ', title: 'タイトル', content: '内容' },
  placeholder: { searchPhrase: '定型文を検索…' },
  empty: { noCategories: 'カテゴリはまだありません', quickJump: 'カテゴリへ移動', noResults: '一致する項目はありません', noPhrases: '定型文はまだありません', noGroups: 'グループはまだありません', uncategorized: '未分類' },
  defaults: { groupName: '新しいグループ', newGroup: '新しいグループ', categoryName: '新しいカテゴリ', newCategory: '新しいカテゴリ', uncategorized: '未分類', newPhrase: '新しい定型文', copySuffix: '（コピー）', iflytekGroupName: 'iFlytek入力メソッドから', importGroupName: 'インポートしたデータ' },
  dialog: { unsavedChanges: '保存されていない変更', unsavedContent: '内容がまだ保存されていません。変更を保存しますか？', unsavedContentNote: '保存しない変更は失われます。', discard: '保存しない', thinkAgain: '編集を続ける', save: '保存', exportTitle: '定型文のバックアップを書き出す', exportIflytekTitle: 'iFlytek入力メソッド形式で書き出す', importTitle: '定型文のバックアップを読み込む', jsonFilter: 'JSONファイル', csvFilter: 'CSVファイル', allSupportedFilter: '対応ファイル' },
  count: { categories: '{count}カテゴリ', characters: '{count}文字', selected: '{count}件を選択中', batchSelected: '選択中：カテゴリ{categories}件、定型文{phrases}件' },
  section: { groups: '定型文グループ' }, file: { backupName: '定型文バックアップ-{date}.json', iflytekBackupName: '定型文バックアップ-{date}.csv' },
  common: { cancel: 'キャンセル', apply: '適用', close: '閉じる', copy: 'コピー', listSeparator: '、', groupSeparator: '；', labelSeparator: '：' },
  settings: { title: '設定', language: '表示言語', languageAuto: '自動（システムに合わせる）', themeMode: 'テーマ', themeLight: 'ライト', themeDark: 'ダーク', themeAuto: 'システム設定を使用', startupSelection: '起動時に開く場所', startupLast: '前回開いていた場所', startupFirst: '並び順の先頭', previewLinesLabel: 'カードのプレビュー行数', previewLines: 'カードのプレビュー行数：{count}', aiModel: 'AIモデル', defaultAiModel: '既定のモデル', aiPrompts: 'AIプロンプト', aiCategorizePrompt: '分類用プロンプト', aiTitlePrompt: 'タイトル用プロンプト', aiContentPrompt: '内容生成用プロンプト', updated: '更新しました：{items}' },
  ai: {
    categorize: 'AIで分類', generateTitle: 'AIでタイトルを作成', generateContent: 'AIで内容を作成', optimizeContent: 'AIで内容を改善', themeGeneration: 'テーマからAI生成', newGeneration: '新しく作成', optimizeExisting: '現在の内容を改善', useAsTheme: 'これをテーマにする', optimizeDescription: '現在の内容を、より明快で読みやすい文章に整えます。', extraRequirementsLabel: '追加の要望（任意）', descriptionLabel: '必要な内容を説明してください', extraRequirementsPlaceholder: '例：より丁寧な文体にして、お礼の言葉を加える…', descriptionPlaceholder: '例：残業を断るメール、顧客へのお礼のメッセージ…', contentApplied: '内容を適用しました', generating: '生成中…', startOptimize: '改善する', generate: '生成', inputRequired: '先に内容を入力してください', titleGenerated: 'タイトルを生成しました', categorized: '{group} / {category} に分類しました', categorizedCategory: '{category} に分類しました', categoryNotFound: 'カテゴリが見つかりません：{category}', groupNotFound: 'グループが見つかりません：{group}', noSuggestion: 'AIが適切なカテゴリを見つけられませんでした', callFailed: 'AIへのリクエストに失敗しました',
    prompt: { optimizeSystem: 'あなたはプロの文章編集者です。意味を変えずに、ユーザーの文章を明快で自然な、読みやすい文章に整えてください。修正後の文章だけを出力し、説明は加えないでください。', themeSystem: 'あなたはプロのライティングアシスタントです。ユーザーが提示する既存の文章をテーマとして、それに沿った新しい実用的な定型文を作成してください。生成した文章だけを出力し、説明は加えないでください。', themeUser: 'テーマ：\n{content}\n\nこのテーマに沿って新しい文章を作成してください。{extra}', extraRequirements: '\n追加の要望：{prompt}', generateSystem: 'あなたはプロのライティングアシスタントです。ユーザーの説明に基づいて、簡潔で自然な定型文を作成してください。生成した文章だけを出力し、説明は加えないでください。', categorizeSystem: 'あなたは分類アシスタントです。内容に最も合うカテゴリを、次のグループとカテゴリ構成から選んでください。\n構成：{structure}\n次の形式のJSONだけを出力してください：{"分组":"グループ名","分类":"カテゴリ名"}', titleSystem: 'あなたはタイトル作成アシスタントです。内容を正確に表す短いタイトルを15文字以内で作成してください。タイトルだけを出力してください。' }
  },
  accessibility: { copyPhrase: '{title}。Enterキーで内容をコピーします。' }, dynamic: { group: 'グループ', category: 'カテゴリ', phrase: '定型文', explain: '定型文を開く／コピー' }, error: { emptyFile: 'ファイルが空です', uncaught: '捕捉されていないエラー', unhandledPromise: '未処理の非同期エラー', renderTitle: 'Reactの描画エラー' },
  help: {
    sectionHierarchy: '📚 データの構成', hierarchyGroup: 'グループ', hierarchyGroupDesc: '最上位', hierarchyCategory: 'カテゴリ', hierarchyCategoryDesc: '整理用フォルダ', hierarchyPhrase: '定型文', hierarchyPhraseDesc: '再利用する内容',
    sectionFeatures: '✨ 機能', featureCopyTitle: 'ワンクリックでコピー', featureCopyDesc: 'カードをクリックすると内容がクリップボードにコピーされ、すぐに貼り付けられます。', featureEditTitle: 'すばやく編集', featureEditDesc: 'カードにポインターを合わせて {key} を押すと、すぐに編集できます。', featureDeleteTitle: '削除と元に戻す', featureDeleteDesc: 'ポインターを合わせて {delKey} で削除、{ctrlKey}+{zKey} で元に戻します。', featureDragTitle: 'ドラッグして移動', featureDragDesc: 'カードを移動先のカテゴリへドラッグします。{key} を押しながらドラッグするとコピーできます。', featureSearchTitle: '全体を検索', featureSearchDesc: 'すべてのグループを検索し、結果をクリックするとその場所へ移動します。', featureBatchTitle: '複数選択', featureBatchDesc: '検索欄の右にある四角いアイコンから、複数の項目をまとめて削除、移動、エクスポートできます。', featurePreviewTitle: 'プレビューモード', featurePreviewDesc: 'カードにポインターを合わせて {key} を1回押すとプレビューモードが切り替わります。上下キーでカードを移動できます。', featureAutoSaveTitle: '自動保存', featureAutoSaveDesc: '編集後に余白をクリックするか別のカードへ移動すると、自動的に保存されます。', featureThemeTitle: 'テーマ', featureThemeDesc: '設定からライト、ダーク、またはシステムに合わせるテーマを選べます。',
    sectionShortcuts: '⌨️ キーボードショートカット', shortcutNewPhrase: '新しい定型文', shortcutNewCategory: '新しいカテゴリ', shortcutFocusSearch: '検索欄へ移動', shortcutForceSave: 'すぐに保存', shortcutUndo: '元に戻す', shortcutRedo: 'やり直す', shortcutSelectAll: 'すべて選択（複数選択時）', shortcutClone: 'ポイント中の項目を複製', shortcutCopy: 'ポイント中の項目をコピー', shortcutEdit: 'ポイント中の項目を編集', shortcutDelete: 'ポイント中の項目を削除', shortcutEscape: '終了／キャンセル', shortcutFullscreen: '全画面で編集', shortcutPreview: 'プレビューモードを切り替え', shortcutDragCopy: '移動先へコピー', dragAction: 'ドラッグ', startGuide: 'チュートリアルを開始'
  },
  guide: {
    steps: {
      step1Title: '🗂️ グループ（最上位）', step1Message: 'グループを使うと、大きな用途ごとに内容を分けて管理できます。\n\n• {bold:作成}：上にある {key:+} ボタンをクリックします。\n• {bold:切り替え}：グループをクリックすると、そのカテゴリが表示されます。\n• {bold:並べ替え}：グループを長押しして左右へドラッグします。\n• {bold:その他}：グループを右クリックすると、{bold:名前の変更}、{bold:削除}、位置の変更ができます。',
      step2Title: '📂 カテゴリと右クリックメニュー', step2Message: '現在のグループにあるカテゴリがここに表示されます。\n\n• {bold:カテゴリを作成}：カテゴリのプルダウンから「新しいカテゴリ…」を選び、入力欄に任意の名前を入力して確定します。先にグループを作成または選択してください。\n• {bold:右クリックメニュー}：カテゴリを右クリックすると、{bold:名前の変更}、{bold:先頭へ移動}、{bold:削除}ができます。\n• {bold:すばやく名前を変更}：カテゴリを選択して {key:F2} を押します。\n• {bold:ドラッグ操作}：上下にドラッグして並べ替えるか、別のグループへドロップして移動します。\n• {bold:名前のルール}：空の名前は登録できず、重複した名前は警告されます。',
      step3Title: '📝 定型文の基本操作', step3Message: 'ここがメインの作業領域です。\n\n• {bold:コピー}：カードをクリックすると内容をコピーします。\n• {bold:ショートカット}：\n   - {key:Ctrl} + {key:C} コピー\n   - {key:Ctrl} + {key:D} 複製\n   - {key:Del} 選択項目を削除\n• {bold:並べ替え}：カードを上下へドラッグします。\n• {bold:カテゴリ間の移動}：カードを左側のカテゴリへドロップします。{key:Ctrl} を押しながらドラッグするとコピーになります。\n• {bold:プレビュー}：カードにポインターを合わせて {key:Space} を1回押し、上下キーで切り替えます。',
      step4Title: '🔍 検索と複数選択', step4Message: '上部のツールバーからすべての内容へアクセスできます。\n\n• {bold:全体検索}（{key:Ctrl} + {key:F}）：すべてのグループを検索し、結果をクリックして移動します。\n• {bold:複数選択}：右側の四角いアイコンをクリックします。\n   - {key:Shift} を押しながら範囲選択\n   - 下部のツールバーから、選択したデータを{bold:削除}、{bold:移動}、{bold:エクスポート}できます。',
      step5Title: '⚙️ バックアップと設定', step5Message: '下部のツールバーに重要な機能があります。\n\n• {bold:インポート／エクスポート}：データを守るため、定期的にJSONバックアップを書き出してください。\n• {bold:設定}：言語、テーマ、起動時の場所、カードのプレビュー行数を変更できます。\n• {bold:ヘルプ}：疑問符をクリックすると、このチュートリアルをもう一度開けます。'
    },
    controls: { skip: 'スキップ', back: '戻る', next: '次へ', finish: '完了' },
    demo: { groupName: '✨ チュートリアル', categoryName: '📝 サンプルカテゴリ', phraseTitle: '👋 ようこそ！', phraseContent: 'これはサンプルの定型文です。クリックしてコピーしたり、ドラッグしたりしてみましょう。', phraseTitle2: '⌨️ ショートカット', phraseContent2: '選択してCtrl+Cでコピー、Ctrl+Dで複製、Deleteで削除できます。', phraseTitle3: '🖱️ ドラッグと移動', phraseContent3: '長押しして並べ替えたり、左側の別のカテゴリへ移動したりできます。' }
  }
}
