export default {
  app: { title: '상용구 관리' },
  snackbar: {
    selectParentCategoryFirst: '먼저 그룹을 선택하세요', categoryDeleted: '카테고리를 삭제했습니다', categoryNameExists: '같은 이름의 카테고리가 이미 있습니다', categoryCreated: '카테고리를 만들었습니다', categoryUpdated: '카테고리를 업데이트했습니다', groupNameExists: '같은 이름의 그룹이 이미 있습니다', groupCreated: '그룹을 만들었습니다', groupUpdated: '그룹을 업데이트했습니다', groupDeleted: '그룹을 삭제했습니다', noGroup: '먼저 그룹을 만들거나 선택하세요', undone: '작업을 실행 취소했습니다', redone: '작업을 다시 실행했습니다',
    noChanges: '변경된 내용이 없습니다', duplicatePhrase: '같은 상용구가 이미 있습니다', phraseCreated: '상용구를 만들었습니다', phraseUpdated: '변경 사항을 저장했습니다', phraseDeleted: '상용구를 삭제했습니다', titleEmpty: '제목을 입력해 주세요', contentEmpty: '내용이 비어 있습니다', saveFailed: '저장하지 못했습니다. 다시 시도해 주세요.', copiedToClipboard: '클립보드에 복사했습니다', createCategoryFirst: '먼저 카테고리를 만드세요', itemsDeleted: '{count}개 항목을 삭제했습니다', phrasesMoved: '상용구 {count}개를 이동했습니다', movedToTop: '맨 위로 이동했습니다', movedToBottom: '맨 아래로 이동했습니다', batchMovedToTop: '선택한 항목을 맨 위로 이동했습니다', batchMovedToBottom: '선택한 항목을 맨 아래로 이동했습니다', phraseCloned: '상용구를 복제했습니다', clonedToCategory: '새 카테고리로 복사했습니다', movedToCategory: '새 카테고리로 이동했습니다',
    categoryCopiedToGroup: '카테고리를 새 그룹으로 복사했습니다', categoryMovedToGroup: '카테고리를 새 그룹으로 이동했습니다', categoriesCopiedToGroup: '카테고리 {count}개를 새 그룹으로 복사했습니다', categoriesMovedToGroup: '카테고리 {count}개를 새 그룹으로 이동했습니다', copiedToUncategorized: '‘미분류’로 복사했습니다', movedToUncategorized: '‘미분류’로 이동했습니다', phrasesCopiedToUncategorized: '상용구 {count}개를 ‘미분류’로 복사했습니다', phrasesMovedToUncategorized: '상용구 {count}개를 ‘미분류’로 이동했습니다',
    exportSuccess: '내보내기를 완료했습니다', exportFailed: '내보내지 못했습니다: {error}', importSuccess: '카테고리 {categories}개와 상용구 {phrases}개를 가져왔습니다', importFailed: '가져오지 못했습니다: {error}', batchExportSuccess: '카테고리 {categories}개와 상용구 {phrases}개를 내보냈습니다', iflytekImportSuccess: 'iFlytek 입력기에서 카테고리 {categories}개와 상용구 {phrases}개를 가져왔습니다', iflytekExportSuccess: 'iFlytek 입력기 형식으로 내보냈습니다', batchMovedToGroup: '카테고리 {categories}개와 상용구 {phrases}개를 그룹으로 이동했습니다', guideCompleted: '사용 안내를 마쳤습니다! 앱을 둘러볼 수 있도록 예제 데이터를 준비했습니다.', cloudUpdatedDraftPreserved: '클라우드 데이터가 업데이트되었습니다. 현재 편집 중인 내용은 덮어쓰지 않았습니다.'
  },
  tooltip: { newCategory: '새 카테고리 (Ctrl+Shift+N)', newPhrase: '새 상용구 (Ctrl+N)', help: '도움말', switchToLight: '밝은 테마', switchToDark: '어두운 테마', import: '가져오기', export: '내보내기', sort: '정렬', batchMode: '여러 항목 선택', selectAll: '모두 선택 / 선택 해제', moveToCategory: '카테고리로 이동', moveToTop: '맨 위로 이동', moveToBottom: '맨 아래로 이동', delete: '삭제', exit: '나가기', clone: '복제', edit: '편집', newGroup: '새 그룹', fullscreen: '전체 화면 편집', exitFullscreen: '전체 화면 종료', exitEdit: '편집기 닫기', settings: '설정' },
  menu: { rename: '이름 바꾸기', moveToTop: '맨 위로 이동', moveToBottom: '맨 아래로 이동', delete: '삭제', copyContent: '내용 복사', clone: '복제', edit: '편집', sortCustom: '사용자 지정 순서', sortUsageDesc: '사용 횟수 많은 순', sortUsageAsc: '사용 횟수 적은 순', sortCreatedDesc: '최근 생성 순', sortCreatedAsc: '오래된 생성 순', sortUpdatedDesc: '최근 수정 순', sortUpdatedAsc: '오래된 수정 순', sortTitleAsc: '제목 (A–Z)', sortTitleDesc: '제목 (Z–A)', newGroup: '새 그룹…', newCategory: '새 카테고리…', exportNative: 'JSON으로 내보내기', exportIflytek: 'iFlytek 형식으로 내보내기' },
  label: { group: '그룹', category: '카테고리', title: '제목', content: '내용' }, placeholder: { searchPhrase: '상용구 검색…' }, empty: { noCategories: '아직 카테고리가 없습니다', quickJump: '카테고리로 빠르게 이동', noResults: '일치하는 결과가 없습니다', noPhrases: '아직 상용구가 없습니다', noGroups: '아직 그룹이 없습니다', uncategorized: '미분류' },
  defaults: { groupName: '새 그룹', newGroup: '새 그룹', categoryName: '새 카테고리', newCategory: '새 카테고리', uncategorized: '미분류', newPhrase: '새 상용구', copySuffix: ' (사본)', iflytekGroupName: 'iFlytek 입력기에서 가져옴', importGroupName: '가져온 데이터' },
  dialog: { unsavedChanges: '저장하지 않은 변경 사항', unsavedContent: '현재 내용을 저장하지 않았습니다. 변경 사항을 저장할까요?', unsavedContentNote: '저장하지 않은 내용은 사라집니다.', discard: '저장 안 함', thinkAgain: '계속 편집', save: '저장', exportTitle: '상용구 백업 내보내기', exportIflytekTitle: 'iFlytek 입력기 형식으로 내보내기', importTitle: '상용구 백업 가져오기', jsonFilter: 'JSON 파일', csvFilter: 'CSV 파일', allSupportedFilter: '지원되는 파일' },
  count: { categories: '카테고리 {count}개', characters: '{count}자', selected: '{count}개 항목 선택됨', batchSelected: '카테고리 {categories}개, 상용구 {phrases}개 선택됨' }, section: { groups: '상용구 그룹' }, file: { backupName: '상용구-백업-{date}.json', iflytekBackupName: '상용구-백업-{date}.csv' },
  common: { cancel: '취소', apply: '적용', close: '닫기', copy: '복사', listSeparator: ', ', groupSeparator: '; ', labelSeparator: ': ' },
  settings: { title: '설정', language: '표시 언어', languageAuto: '자동 (시스템 언어)', themeMode: '테마', themeLight: '밝게', themeDark: '어둡게', themeAuto: '시스템 설정 사용', startupSelection: '시작할 때 열 위치', startupLast: '마지막으로 본 위치', startupFirst: '정렬 순서의 첫 항목', previewLinesLabel: '카드 미리보기 줄 수', previewLines: '카드 미리보기 줄 수: {count}', aiModel: 'AI 모델', defaultAiModel: '기본 모델', aiPrompts: 'AI 프롬프트', aiCategorizePrompt: '분류 프롬프트', aiTitlePrompt: '제목 프롬프트', aiContentPrompt: '콘텐츠 생성 프롬프트', updated: '업데이트됨: {items}' },
  ai: {
    categorize: 'AI로 분류', generateTitle: 'AI로 제목 생성', generateContent: 'AI로 내용 생성', optimizeContent: 'AI로 내용 다듬기', themeGeneration: '주제로 AI 생성', newGeneration: '새로 생성', optimizeExisting: '기존 내용 다듬기', useAsTheme: '이 내용을 주제로 사용', optimizeDescription: '기존 내용을 더 명확하고 전문적인 문장으로 다듬습니다.', extraRequirementsLabel: '추가 요청 (선택 사항)', descriptionLabel: '필요한 내용을 설명하세요', extraRequirementsPlaceholder: '예: 더 격식 있는 어조로 바꾸고 감사 인사 추가…', descriptionPlaceholder: '예: 야근을 거절하는 이메일, 고객에게 보내는 감사 인사…', contentApplied: '내용을 적용했습니다', generating: '생성 중…', startOptimize: '다듬기', generate: '생성', inputRequired: '먼저 내용을 입력하세요', titleGenerated: '제목을 생성했습니다', categorized: '{group} / {category}(으)로 분류했습니다', categorizedCategory: '{category}(으)로 분류했습니다', categoryNotFound: '카테고리를 찾을 수 없습니다: {category}', groupNotFound: '그룹을 찾을 수 없습니다: {group}', noSuggestion: 'AI가 알맞은 카테고리를 찾지 못했습니다', callFailed: 'AI 요청에 실패했습니다',
    prompt: { optimizeSystem: '당신은 전문 문장 편집자입니다. 원래 의미는 유지하면서 사용자의 글을 더 명확하고 자연스럽고 체계적인 문장으로 다듬으세요. 설명 없이 수정한 내용만 출력하세요.', themeSystem: '당신은 전문 글쓰기 도우미입니다. 사용자가 기존 내용을 주제로 제공합니다. 그 주제를 바탕으로 새롭고 자연스러운 상용구를 작성하세요. 설명 없이 새 내용만 출력하세요.', themeUser: '주제:\n{content}\n\n이 주제를 바탕으로 새 내용을 작성하세요.{extra}', extraRequirements: '\n추가 요청: {prompt}', generateSystem: '당신은 전문 글쓰기 도우미입니다. 사용자의 설명에 따라 간결하고 자연스러운 상용구를 작성하세요. 설명 없이 생성한 내용만 출력하세요.', categorizeSystem: '당신은 분류 도우미입니다. 내용을 바탕으로 아래 그룹 및 카테고리 구조에서 가장 적합한 카테고리를 고르세요.\n구조: {structure}\n다음 형식의 JSON만 출력하세요: {"分组":"그룹 이름","分类":"카테고리 이름"}', titleSystem: '당신은 제목 작성 도우미입니다. 내용을 정확히 나타내는 짧은 제목을 15단어 이내로 작성하세요. 제목만 출력하세요.' }
  },
  accessibility: { copyPhrase: '{title}. Enter 키를 누르면 내용을 복사합니다.' }, dynamic: { group: '그룹', category: '카테고리', phrase: '상용구', explain: '상용구 열기 또는 복사' }, error: { emptyFile: '파일이 비어 있습니다', uncaught: '처리되지 않은 오류', unhandledPromise: '처리되지 않은 비동기 오류', renderTitle: 'React 렌더링 오류' },
  help: {
    sectionHierarchy: '📚 데이터 구성', hierarchyGroup: '그룹', hierarchyGroupDesc: '최상위', hierarchyCategory: '카테고리', hierarchyCategoryDesc: '정리용 폴더', hierarchyPhrase: '상용구', hierarchyPhraseDesc: '재사용할 내용',
    sectionFeatures: '✨ 기능', featureCopyTitle: '한 번에 복사', featureCopyDesc: '카드를 클릭하면 내용을 클립보드에 복사해 바로 붙여넣을 수 있습니다.', featureEditTitle: '빠른 편집', featureEditDesc: '카드 위에 마우스를 올리고 {key} 키를 누르면 바로 편집할 수 있습니다.', featureDeleteTitle: '삭제 및 실행 취소', featureDeleteDesc: '마우스를 올린 상태에서 {delKey} 키로 삭제하고 {ctrlKey}+{zKey} 키로 실행 취소합니다.', featureDragTitle: '끌어서 이동', featureDragDesc: '카드를 대상 카테고리로 끌어 놓으세요. {key} 키를 누른 채 끌면 복사됩니다.', featureSearchTitle: '전체 검색', featureSearchDesc: '모든 그룹을 검색하고 결과를 클릭하면 해당 위치로 바로 이동합니다.', featureBatchTitle: '여러 항목 선택', featureBatchDesc: '검색창 옆 사각형 아이콘을 눌러 여러 항목을 한꺼번에 선택, 삭제, 이동 또는 내보낼 수 있습니다.', featurePreviewTitle: '미리보기 모드', featurePreviewDesc: '카드에 마우스를 올리고 {key} 키를 한 번 누르면 미리보기 모드가 켜지거나 꺼집니다. 위아래 방향키로 카드를 전환하세요.', featureAutoSaveTitle: '자동 저장', featureAutoSaveDesc: '편집 후 바깥을 클릭하거나 다른 카드로 이동하면 자동으로 저장됩니다.', featureThemeTitle: '테마', featureThemeDesc: '설정에서 밝은 테마, 어두운 테마 또는 시스템 설정 사용을 선택할 수 있습니다.',
    sectionShortcuts: '⌨️ 키보드 단축키', shortcutNewPhrase: '새 상용구', shortcutNewCategory: '새 카테고리', shortcutFocusSearch: '검색창으로 이동', shortcutForceSave: '바로 저장', shortcutUndo: '실행 취소', shortcutRedo: '다시 실행', shortcutSelectAll: '모두 선택 (다중 선택 모드)', shortcutClone: '가리킨 항목 복제', shortcutCopy: '가리킨 항목 복사', shortcutEdit: '가리킨 항목 편집', shortcutDelete: '가리킨 항목 삭제', shortcutEscape: '나가기 / 취소', shortcutFullscreen: '전체 화면 편집', shortcutPreview: '미리보기 모드 전환', shortcutDragCopy: '대상에 복사', dragAction: '끌기', startGuide: '사용 안내 시작'
  },
  guide: {
    steps: {
      step1Title: '🗂️ 그룹 (최상위)', step1Message: '그룹을 사용하면 큰 업무 영역별로 내용을 나눠 관리할 수 있습니다.\n\n• {bold:만들기}: 위쪽의 {key:+} 버튼을 누르세요.\n• {bold:전환}: 그룹을 클릭하면 해당 그룹의 카테고리가 표시됩니다.\n• {bold:정렬}: 그룹을 길게 눌러 좌우로 끄세요.\n• {bold:더보기}: 그룹을 마우스 오른쪽 버튼으로 클릭해 {bold:이름 바꾸기}, {bold:삭제}, 위치 변경을 할 수 있습니다.',
      step2Title: '📂 카테고리와 메뉴', step2Message: '현재 그룹의 모든 카테고리가 여기에 표시됩니다.\n\n• {bold:카테고리 만들기}: 카테고리 목록을 열고 “새 카테고리…”를 선택한 뒤 입력란에 원하는 이름을 입력하고 확인하세요. 먼저 그룹을 만들거나 선택해야 합니다.\n• {bold:상황에 맞는 메뉴}: 카테고리를 마우스 오른쪽 버튼으로 클릭해 {bold:이름 바꾸기}, {bold:맨 위로 이동}, {bold:삭제}를 할 수 있습니다.\n• {bold:빠른 이름 바꾸기}: 카테고리를 선택하고 {key:F2} 키를 누르세요.\n• {bold:끌어서 관리}: 위아래로 끌어 정렬하거나 다른 그룹에 놓아 이동할 수 있습니다.\n• {bold:이름 규칙}: 이름은 비워 둘 수 없으며 중복 이름은 경고됩니다.',
      step3Title: '📝 상용구 기본 작업', step3Message: '이곳이 기본 작업 공간입니다.\n\n• {bold:복사}: 카드를 클릭하면 내용을 복사합니다.\n• {bold:단축키}:\n   - {key:Ctrl} + {key:C} 복사\n   - {key:Ctrl} + {key:D} 복제\n   - {key:Del} 선택 항목 삭제\n• {bold:정렬}: 카드를 위아래로 끄세요.\n• {bold:카테고리 간 이동}: 카드를 왼쪽 카테고리에 놓으세요. {key:Ctrl} 키를 누른 채 끌면 복사됩니다.\n• {bold:미리보기}: 카드에 마우스를 올리고 {key:Space} 키를 한 번 누른 다음 위아래 방향키로 전환하세요.',
      step4Title: '🔍 검색과 여러 항목 선택', step4Message: '위쪽 도구 모음에서 모든 내용에 접근할 수 있습니다.\n\n• {bold:전체 검색} ({key:Ctrl} + {key:F}): 모든 그룹에서 찾아 결과를 클릭하면 해당 위치로 이동합니다.\n• {bold:여러 항목 선택}: 오른쪽 사각형 아이콘을 클릭하세요.\n   - {key:Shift} 키를 누른 채 범위 선택\n   - 아래쪽 도구 모음에서 선택한 데이터를 {bold:삭제}, {bold:이동}, {bold:내보내기}할 수 있습니다.',
      step5Title: '⚙️ 백업 및 설정', step5Message: '아래쪽 도구 모음에 주요 기능이 모여 있습니다.\n\n• {bold:가져오기 / 내보내기}: 데이터 보호를 위해 정기적으로 JSON 백업을 내보내세요.\n• {bold:설정}: 언어, 테마, 시작 위치, 카드 미리보기 줄 수를 조정할 수 있습니다.\n• {bold:도움말}: 물음표를 클릭하면 이 안내를 다시 볼 수 있습니다.'
    },
    controls: { skip: '건너뛰기', back: '이전', next: '다음', finish: '완료' },
    demo: { groupName: '✨ 사용 안내 그룹', categoryName: '📝 예제 카테고리', phraseTitle: '👋 환영합니다!', phraseContent: '예제 상용구입니다. 클릭해 복사하거나 직접 끌어 보세요.', phraseTitle2: '⌨️ 단축키 활용', phraseContent2: '저를 선택하고 Ctrl+C로 복사, Ctrl+D로 복제하거나 Delete로 삭제해 보세요.', phraseTitle3: '🖱️ 끌기와 이동', phraseContent3: '길게 눌러 순서를 바꾸거나 왼쪽의 다른 카테고리로 이동할 수 있습니다.' }
  }
}
