import ptPT from './pt-PT'
import { mergeLocale } from './mergeLocale'

export default mergeLocale(ptPT, {
  app: { title: 'Gerenciador de frases' },
  snackbar: {
    categoryDeleted: 'Categoria excluída', groupDeleted: 'Grupo excluído', undone: 'Ação desfeita', redone: 'Ação refeita', noChanges: 'Não há alterações para salvar', phraseUpdated: 'Alterações salvas', phraseDeleted: 'Frase excluída', titleEmpty: 'O título não pode ficar vazio', saveFailed: 'Não foi possível salvar. Tente novamente.', itemsDeleted: { one: '{count} item excluído', other: '{count} itens excluídos' }, batchMovedToTop: 'Itens selecionados movidos para o topo', phraseCloned: 'Frase duplicada', guideCompleted: 'Você concluiu o guia! Adicionamos alguns dados de exemplo para você explorar o aplicativo.', cloudUpdatedDraftPreserved: 'Os dados na nuvem foram atualizados. Seu rascunho atual não foi substituído.'
  },
  tooltip: { moveToTop: 'Mover para o topo', delete: 'Excluir', fullscreen: 'Editor em tela cheia', exitFullscreen: 'Sair da tela cheia', exitEdit: 'Fechar editor', settings: 'Configurações' },
  menu: { moveToTop: 'Mover para o topo', delete: 'Excluir', sortUpdatedDesc: 'Editadas recentemente primeiro', newGroup: 'Novo grupo…', newCategory: 'Nova categoria…' },
  dialog: { unsavedChanges: 'Alterações não salvas', unsavedContent: 'Este conteúdo ainda não foi salvo. Deseja salvar as alterações?', unsavedContentNote: 'As alterações não salvas serão perdidas.', discard: 'Não salvar', thinkAgain: 'Continuar editando', save: 'Salvar', jsonFilter: 'Arquivos JSON', csvFilter: 'Arquivos CSV', allSupportedFilter: 'Arquivos compatíveis' },
  count: { characters: { one: '{count} caractere', other: '{count} caracteres' } },
  settings: { title: 'Configurações', language: 'Idioma da interface', languageAuto: 'Automático (idioma do sistema)', themeAuto: 'Usar configuração do sistema', startupLast: 'Último local visitado', startupFirst: 'Primeiro item da ordem', previewLinesLabel: 'Linhas de visualização dos cartões', previewLines: 'Linhas de visualização: {count}', defaultAiModel: 'Modelo padrão', aiPrompts: 'Prompts de IA', aiCategorizePrompt: 'Prompt de categorização', aiTitlePrompt: 'Prompt de título', aiContentPrompt: 'Prompt de geração de conteúdo' },
  ai: {
    optimizeExisting: 'Melhorar texto atual', optimizeDescription: 'A IA deixará o conteúdo atual mais claro e profissional.', extraRequirementsLabel: 'Instruções adicionais (opcional)', descriptionLabel: 'Descreva o conteúdo de que você precisa', extraRequirementsPlaceholder: 'Por exemplo: use um tom mais formal e acrescente um agradecimento…', descriptionPlaceholder: 'Por exemplo: uma mensagem para recusar horas extras ou agradecer a um cliente…', generating: 'Gerando…', inputRequired: 'Digite primeiro algum conteúdo',
    prompt: { optimizeSystem: 'Você é um revisor profissional. Melhore o texto do usuário para que fique claro, natural, profissional e bem estruturado, sem alterar o significado. Retorne apenas o texto revisado, sem comentários.', themeSystem: 'Você é um assistente de escrita profissional. O usuário fornecerá um texto existente como tema. Escreva uma nova frase reutilizável, natural e profissional com base nesse tema. Retorne apenas o novo texto, sem comentários.', themeUser: 'Tema:\n{content}\n\nEscreva um novo conteúdo com base neste tema.{extra}', generateSystem: 'Você é um assistente de escrita profissional. Escreva uma frase reutilizável concisa, natural e profissional com base na descrição do usuário. Retorne apenas o texto gerado, sem comentários.', categorizeSystem: 'Você é um assistente de classificação. Com base no conteúdo, escolha a categoria mais adequada na estrutura de grupos e categorias abaixo.\nEstrutura: {structure}\nRetorne apenas JSON neste formato exato: {"分组":"nome do grupo","分类":"nome da categoria"}', titleSystem: 'Você é um assistente de criação de títulos. Escreva um título curto e preciso para o conteúdo, com no máximo 15 palavras. Retorne apenas o título.' }
  },
  accessibility: { copyPhrase: '{title}. Pressione Enter para copiar o conteúdo.' },
  error: { emptyFile: 'O arquivo está vazio', uncaught: 'Erro não capturado', unhandledPromise: 'Erro assíncrono não tratado', renderTitle: 'Erro de renderização do React' },
  help: {
    sectionFeatures: '✨ Recursos', hierarchyCategoryDesc: 'Pasta de organização', featureCopyDesc: 'Clique em um cartão para copiar o conteúdo para a área de transferência, pronto para colar.', featureEditDesc: 'Passe o mouse sobre um cartão e pressione {key} para editá-lo imediatamente.', featureDeleteTitle: 'Excluir e desfazer', featureDeleteDesc: 'Com o ponteiro sobre o cartão, pressione {delKey} para excluir ou {ctrlKey}+{zKey} para desfazer.', featureDragDesc: 'Arraste um cartão para a categoria de destino. Mantenha {key} pressionada ao arrastar para copiá-lo.', featureSearchDesc: 'Pesquise em todos os grupos e clique em um resultado para ir diretamente até ele.', featureBatchDesc: 'Use o ícone quadrado ao lado da busca para selecionar, excluir, mover ou exportar vários itens.', featurePreviewTitle: 'Modo de visualização', featurePreviewDesc: 'Passe o mouse sobre um cartão e pressione {key} uma vez para ativar ou desativar a visualização. Use as setas para cima e para baixo para mudar de cartão.', featureAutoSaveTitle: 'Salvamento automático', featureAutoSaveDesc: 'Depois de editar, clique fora do editor ou mude de cartão para salvar automaticamente.', featureThemeDesc: 'Abra as Configurações para escolher um tema claro, escuro ou seguir o sistema.', sectionShortcuts: '⌨️ Atalhos de teclado', shortcutForceSave: 'Salvar agora', shortcutUndo: 'Desfazer', shortcutRedo: 'Refazer', shortcutClone: 'Duplicar item sob o ponteiro', shortcutDelete: 'Excluir item sob o ponteiro', shortcutFullscreen: 'Editor em tela cheia', shortcutPreview: 'Alternar visualização', dragAction: 'Arrastar', startGuide: 'Iniciar guia'
  },
  guide: {
    steps: {
      step1Message: 'Os grupos mantêm separadas as principais áreas de trabalho.\n\n• {bold:Criar}: clique no botão {key:+} acima.\n• {bold:Mudar}: clique em um grupo para mostrar suas categorias.\n• {bold:Reordenar}: mantenha um grupo pressionado e arraste-o para a esquerda ou direita.\n• {bold:Mais}: clique com o botão direito em um grupo para {bold:renomear}, {bold:excluir} ou alterar a posição.',
      step2Title: '📂 Categorias e menu de contexto', step2Message: 'Esta coluna mostra as categorias do grupo atual.\n\n• {bold:Menu de contexto}: clique com o botão direito em uma categoria para {bold:renomear}, {bold:mover para o topo} ou {bold:excluir}.\n• {bold:Renomear rapidamente}: selecione uma categoria e pressione {key:F2}.\n• {bold:Arrastar e soltar}: arraste para cima ou para baixo para reordenar, ou solte a categoria em outro grupo para movê-la.',
      step3Message: 'Esta é a área de trabalho principal.\n\n• {bold:Copiar}: clique em um cartão para copiar o conteúdo.\n• {bold:Atalhos}:\n   - {key:Ctrl} + {key:C} copia\n   - {key:Ctrl} + {key:D} duplica\n   - {key:Del} exclui o item selecionado\n• {bold:Reordenar}: arraste os cartões para cima ou para baixo.\n• {bold:Mover entre categorias}: solte um cartão em uma categoria à esquerda; mantenha {key:Ctrl} pressionada ao arrastar para copiá-lo.\n• {bold:Visualizar}: passe o mouse sobre um cartão, pressione {key:Espaço} uma vez e use as setas para cima e para baixo.',
      step4Message: 'A barra superior dá acesso a todo o conteúdo.\n\n• {bold:Busca global} ({key:Ctrl} + {key:F}): pesquise em todos os grupos e clique em um resultado para acessá-lo.\n• {bold:Seleção múltipla}: clique no ícone quadrado à direita.\n   - Mantenha {key:Shift} pressionada para selecionar um intervalo\n   - Use a barra inferior para {bold:excluir}, {bold:mover} ou {bold:exportar} os dados selecionados.',
      step5Title: '⚙️ Backups e configurações', step5Message: 'A barra inferior mantém as ferramentas essenciais por perto.\n\n• {bold:Importar / Exportar}: exporte regularmente um backup JSON para proteger seus dados.\n• {bold:Configurações}: escolha o idioma, o tema, o local inicial e as linhas de visualização.\n• {bold:Ajuda}: clique no ponto de interrogação para abrir este guia novamente.'
    },
    controls: { back: 'Voltar', next: 'Avançar', finish: 'Concluir' },
    demo: { groupName: '✨ Grupo do guia', categoryName: '📝 Categoria de exemplo', phraseTitle: '👋 Boas-vindas!', phraseContent: 'Esta é uma frase de exemplo. Clique para copiar ou experimente arrastá-la.', phraseTitle2: '⌨️ Atalhos de teclado', phraseContent2: 'Selecione-me e pressione Ctrl+C para copiar, Ctrl+D para duplicar ou Delete para excluir.', phraseTitle3: '🖱️ Arrastar e mover', phraseContent3: 'Mantenha pressionado e arraste para reordenar, ou solte em outra categoria à esquerda.' }
  }
})
