export default {
  app: { title: 'Gestor de frases' },
  snackbar: {
    selectParentCategoryFirst: 'Selecione primeiro um grupo', categoryDeleted: 'Categoria eliminada', categoryNameExists: 'Já existe uma categoria com este nome', categoryCreated: 'Categoria criada', categoryUpdated: 'Categoria atualizada', groupNameExists: 'Já existe um grupo com este nome', groupCreated: 'Grupo criado', groupUpdated: 'Grupo atualizado', groupDeleted: 'Grupo eliminado', noGroup: 'Crie ou selecione primeiro um grupo', undone: 'Ação anulada', redone: 'Ação refeita',
    noChanges: 'Não há alterações para guardar', duplicatePhrase: 'Já existe uma frase idêntica', phraseCreated: 'Frase criada', phraseUpdated: 'Alterações guardadas', phraseDeleted: 'Frase eliminada', titleEmpty: 'O título não pode ficar vazio', contentEmpty: 'O conteúdo está vazio', saveFailed: 'Não foi possível guardar. Tente novamente.', copiedToClipboard: 'Copiado para a área de transferência', createCategoryFirst: 'Crie primeiro uma categoria', itemsDeleted: { one: '{count} item eliminado', other: '{count} itens eliminados' }, phrasesMoved: { one: '{count} frase movida', other: '{count} frases movidas' }, movedToTop: 'Movido para o início', movedToBottom: 'Movido para o fim', batchMovedToTop: 'Itens selecionados movidos para o início', batchMovedToBottom: 'Itens selecionados movidos para o fim', phraseCloned: 'Frase duplicada', clonedToCategory: 'Copiado para a nova categoria', movedToCategory: 'Movido para a nova categoria',
    categoryCopiedToGroup: 'Categoria copiada para o novo grupo', categoryMovedToGroup: 'Categoria movida para o novo grupo', categoriesCopiedToGroup: { one: '{count} categoria copiada para o novo grupo', other: '{count} categorias copiadas para o novo grupo' }, categoriesMovedToGroup: { one: '{count} categoria movida para o novo grupo', other: '{count} categorias movidas para o novo grupo' }, copiedToUncategorized: 'Copiado para «Sem categoria»', movedToUncategorized: 'Movido para «Sem categoria»', phrasesCopiedToUncategorized: { one: '{count} frase copiada para «Sem categoria»', other: '{count} frases copiadas para «Sem categoria»' }, phrasesMovedToUncategorized: { one: '{count} frase movida para «Sem categoria»', other: '{count} frases movidas para «Sem categoria»' },
    exportSuccess: 'Exportação concluída', exportFailed: 'Não foi possível exportar: {error}', importSuccess: 'Importação concluída. Categorias: {categories}; frases: {phrases}', importFailed: 'Não foi possível importar: {error}', batchExportSuccess: 'Exportação concluída. Categorias: {categories}; frases: {phrases}', iflytekImportSuccess: 'Importação do método de introdução iFlytek concluída. Categorias: {categories}; frases: {phrases}', iflytekExportSuccess: 'Exportado no formato do método de introdução iFlytek', batchMovedToGroup: 'Movido para o grupo. Categorias: {categories}; frases: {phrases}', guideCompleted: 'Concluiu o guia! Adicionámos alguns dados de exemplo para poder explorar a aplicação.', cloudUpdatedDraftPreserved: 'Os dados na nuvem foram atualizados. O rascunho atual não foi substituído.'
  },
  tooltip: { newCategory: 'Nova categoria (Ctrl+Shift+N)', newPhrase: 'Nova frase (Ctrl+N)', help: 'Ajuda', switchToLight: 'Tema claro', switchToDark: 'Tema escuro', import: 'Importar', export: 'Exportar', sort: 'Ordenar', batchMode: 'Seleção múltipla', selectAll: 'Selecionar tudo / Limpar seleção', moveToCategory: 'Mover para categoria', moveToTop: 'Mover para o início', moveToBottom: 'Mover para o fim', delete: 'Eliminar', exit: 'Sair', clone: 'Duplicar', edit: 'Editar', newGroup: 'Novo grupo', fullscreen: 'Editor em ecrã inteiro', exitFullscreen: 'Sair do ecrã inteiro', exitEdit: 'Fechar editor', settings: 'Definições' },
  menu: { rename: 'Mudar nome', moveToTop: 'Mover para o início', moveToBottom: 'Mover para o fim', delete: 'Eliminar', copyContent: 'Copiar conteúdo', clone: 'Duplicar', edit: 'Editar', sortCustom: 'Ordem personalizada', sortUsageDesc: 'Mais utilizadas primeiro', sortUsageAsc: 'Menos utilizadas primeiro', sortCreatedDesc: 'Mais recentes primeiro', sortCreatedAsc: 'Mais antigas primeiro', sortUpdatedDesc: 'Editadas recentemente primeiro', sortUpdatedAsc: 'Editadas há mais tempo primeiro', sortTitleAsc: 'Título (A–Z)', sortTitleDesc: 'Título (Z–A)', newGroup: 'Novo grupo…', newCategory: 'Nova categoria…', exportNative: 'Exportar como JSON', exportIflytek: 'Exportar para o método de introdução iFlytek' },
  label: { group: 'Grupo', category: 'Categoria', title: 'Título', content: 'Conteúdo' }, placeholder: { searchPhrase: 'Pesquisar frases…' }, empty: { noCategories: 'Ainda não há categorias', quickJump: 'Ir para uma categoria', noResults: 'Sem resultados', noPhrases: 'Ainda não há frases', noGroups: 'Ainda não há grupos', uncategorized: 'Sem categoria' },
  defaults: { groupName: 'Novo grupo', newGroup: 'Novo grupo', categoryName: 'Nova categoria', newCategory: 'Nova categoria', uncategorized: 'Sem categoria', newPhrase: 'Nova frase', copySuffix: ' (cópia)', iflytekGroupName: 'Do método de introdução iFlytek', importGroupName: 'Dados importados' },
  dialog: { unsavedChanges: 'Alterações por guardar', unsavedContent: 'Este conteúdo ainda não foi guardado. Pretende guardar as alterações?', unsavedContentNote: 'As alterações não guardadas serão perdidas.', discard: 'Não guardar', thinkAgain: 'Continuar a editar', save: 'Guardar', exportTitle: 'Exportar cópia de segurança das frases', exportIflytekTitle: 'Exportar para o método de introdução iFlytek', importTitle: 'Importar cópia de segurança das frases', jsonFilter: 'Ficheiros JSON', csvFilter: 'Ficheiros CSV', allSupportedFilter: 'Ficheiros suportados' },
  count: { categories: { one: '{count} categoria', other: '{count} categorias' }, characters: { one: '{count} caráter', other: '{count} carateres' }, selected: { one: '{count} item selecionado', other: '{count} itens selecionados' }, batchSelected: 'Seleção — categorias: {categories}; frases: {phrases}' }, section: { groups: 'Grupos de frases' }, file: { backupName: 'copia-frases-{date}.json', iflytekBackupName: 'copia-frases-{date}.csv' },
  common: { cancel: 'Cancelar', apply: 'Aplicar', close: 'Fechar', copy: 'Copiar', listSeparator: ', ', groupSeparator: '; ', labelSeparator: ': ' },
  settings: { title: 'Definições', language: 'Idioma da interface', languageAuto: 'Automático (idioma do sistema)', themeMode: 'Tema', themeLight: 'Claro', themeDark: 'Escuro', themeAuto: 'Usar definição do sistema', startupSelection: 'Abrir ao iniciar', startupLast: 'Última localização consultada', startupFirst: 'Primeiro item da ordem', previewLinesLabel: 'Linhas de pré-visualização dos cartões', previewLines: 'Linhas de pré-visualização: {count}', aiModel: 'Modelo de IA', defaultAiModel: 'Modelo predefinido', aiPrompts: 'Instruções para a IA', aiCategorizePrompt: 'Instrução de categorização', aiTitlePrompt: 'Instrução para o título', aiContentPrompt: 'Instrução para gerar conteúdo', updated: 'Atualizado: {items}' },
  ai: {
    categorize: 'Classificar com IA', generateTitle: 'Gerar título com IA', generateContent: 'Gerar conteúdo com IA', optimizeContent: 'Melhorar conteúdo com IA', themeGeneration: 'Gerar a partir de um tema', newGeneration: 'Criar de raiz', optimizeExisting: 'Melhorar texto existente', useAsTheme: 'Usar como tema', optimizeDescription: 'A IA tornará o conteúdo existente mais claro e profissional.', extraRequirementsLabel: 'Instruções adicionais (opcional)', descriptionLabel: 'Descreva o conteúdo de que precisa', extraRequirementsPlaceholder: 'Por exemplo: usar um tom mais formal e acrescentar um agradecimento…', descriptionPlaceholder: 'Por exemplo: uma mensagem para recusar horas extraordinárias ou agradecer a um cliente…', contentApplied: 'Conteúdo aplicado', generating: 'A gerar…', startOptimize: 'Melhorar', generate: 'Gerar', inputRequired: 'Introduza primeiro algum conteúdo', titleGenerated: 'Título gerado', categorized: 'Classificado em {group} / {category}', categorizedCategory: 'Classificado em {category}', categoryNotFound: 'Categoria não encontrada: {category}', groupNotFound: 'Grupo não encontrado: {group}', noSuggestion: 'A IA não encontrou uma categoria adequada', callFailed: 'O pedido à IA falhou',
    prompt: { optimizeSystem: 'É um revisor profissional. Melhore o texto do utilizador para que fique claro, natural, profissional e bem estruturado, sem alterar o significado. Devolva apenas o texto revisto, sem comentários.', themeSystem: 'É um assistente de escrita profissional. O utilizador fornecerá um texto existente como tema. Escreva uma nova frase reutilizável, natural e profissional com base nesse tema. Devolva apenas o novo texto, sem comentários.', themeUser: 'Tema:\n{content}\n\nEscreva novo conteúdo com base neste tema.{extra}', extraRequirements: '\nInstruções adicionais: {prompt}', generateSystem: 'É um assistente de escrita profissional. Escreva uma frase reutilizável concisa, natural e profissional com base na descrição do utilizador. Devolva apenas o texto gerado, sem comentários.', categorizeSystem: 'É um assistente de classificação. Com base no conteúdo, escolha a categoria mais adequada na estrutura de grupos e categorias abaixo.\nEstrutura: {structure}\nDevolva apenas JSON neste formato exato: {"分组":"nome do grupo","分类":"nome da categoria"}', titleSystem: 'É um assistente de criação de títulos. Escreva um título curto e preciso para o conteúdo, com no máximo 15 palavras. Devolva apenas o título.' }
  },
  accessibility: { copyPhrase: '{title}. Prima Enter para copiar o conteúdo.' }, dynamic: { group: 'Grupo', category: 'Categoria', phrase: 'Frase', explain: 'Abrir ou copiar uma frase' }, error: { emptyFile: 'O ficheiro está vazio', uncaught: 'Erro não detetado', unhandledPromise: 'Erro assíncrono não processado', renderTitle: 'Erro de composição do React' },
  help: {
    sectionHierarchy: '📚 Organização dos dados', hierarchyGroup: 'Grupo', hierarchyGroupDesc: 'Nível superior', hierarchyCategory: 'Categoria', hierarchyCategoryDesc: 'Pasta de organização', hierarchyPhrase: 'Frase', hierarchyPhraseDesc: 'Conteúdo reutilizável',
    sectionFeatures: '✨ Funcionalidades', featureCopyTitle: 'Copiar com um clique', featureCopyDesc: 'Clique num cartão para copiar o conteúdo para a área de transferência, pronto a colar.', featureEditTitle: 'Edição rápida', featureEditDesc: 'Passe o rato sobre um cartão e prima {key} para o editar de imediato.', featureDeleteTitle: 'Eliminar e anular', featureDeleteDesc: 'Com o ponteiro sobre o cartão, prima {delKey} para eliminar ou {ctrlKey}+{zKey} para anular.', featureDragTitle: 'Arrastar para mover', featureDragDesc: 'Arraste um cartão para a categoria de destino. Mantenha {key} premida ao arrastar para o copiar.', featureSearchTitle: 'Pesquisar em todo o lado', featureSearchDesc: 'Pesquise em todos os grupos e clique num resultado para ir diretamente até ele.', featureBatchTitle: 'Seleção múltipla', featureBatchDesc: 'Use o ícone quadrado junto à pesquisa para selecionar, eliminar, mover ou exportar vários itens.', featurePreviewTitle: 'Modo de pré-visualização', featurePreviewDesc: 'Passe o rato sobre um cartão e prima {key} uma vez para ativar ou desativar a pré-visualização. Use as setas Cima e Baixo para mudar de cartão.', featureAutoSaveTitle: 'Gravação automática', featureAutoSaveDesc: 'Depois de editar, clique fora do editor ou mude de cartão para guardar automaticamente.', featureThemeTitle: 'Tema', featureThemeDesc: 'Abra as Definições para escolher um tema claro, escuro ou seguir o sistema.',
    sectionShortcuts: '⌨️ Atalhos de teclado', shortcutNewPhrase: 'Nova frase', shortcutNewCategory: 'Nova categoria', shortcutFocusSearch: 'Ativar pesquisa', shortcutForceSave: 'Guardar agora', shortcutUndo: 'Anular', shortcutRedo: 'Refazer', shortcutSelectAll: 'Selecionar tudo (seleção múltipla)', shortcutClone: 'Duplicar item sob o ponteiro', shortcutCopy: 'Copiar item sob o ponteiro', shortcutEdit: 'Editar item sob o ponteiro', shortcutDelete: 'Eliminar item sob o ponteiro', shortcutEscape: 'Sair / Cancelar', shortcutFullscreen: 'Editor em ecrã inteiro', shortcutPreview: 'Alternar pré-visualização', shortcutDragCopy: 'Copiar para o destino', dragAction: 'Arrastar', startGuide: 'Iniciar guia'
  },
  guide: {
    steps: {
      step1Title: '🗂️ Grupos (nível superior)', step1Message: 'Os grupos mantêm separadas as principais áreas de trabalho.\n\n• {bold:Criar}: clique no botão {key:+} acima.\n• {bold:Mudar}: clique num grupo para mostrar as respetivas categorias.\n• {bold:Reordenar}: mantenha um grupo premido e arraste-o para a esquerda ou direita.\n• {bold:Mais}: clique com o botão direito num grupo para {bold:mudar o nome}, {bold:eliminar} ou alterar a posição.',
      step2Title: '📂 Categorias e menu de contexto', step2Message: 'Esta coluna apresenta as categorias do grupo atual.\n\n• {bold:Menu de contexto}: clique com o botão direito numa categoria para {bold:mudar o nome}, {bold:mover para o início} ou {bold:eliminar}.\n• {bold:Mudar o nome rapidamente}: selecione uma categoria e prima {key:F2}.\n• {bold:Arrastar e largar}: arraste para cima ou para baixo para reordenar, ou largue a categoria noutro grupo para a mover.',
      step3Title: '📝 Trabalhar com frases', step3Message: 'Esta é a área de trabalho principal.\n\n• {bold:Copiar}: clique num cartão para copiar o conteúdo.\n• {bold:Atalhos}:\n   - {key:Ctrl} + {key:C} copia\n   - {key:Ctrl} + {key:D} duplica\n   - {key:Del} elimina o item selecionado\n• {bold:Reordenar}: arraste os cartões para cima ou para baixo.\n• {bold:Mover entre categorias}: largue um cartão numa categoria à esquerda; mantenha {key:Ctrl} premida ao arrastar para o copiar.\n• {bold:Pré-visualizar}: passe o rato sobre um cartão, prima {key:Espaço} uma vez e use as setas Cima e Baixo.',
      step4Title: '🔍 Pesquisa e seleção múltipla', step4Message: 'A barra superior dá acesso a todo o conteúdo.\n\n• {bold:Pesquisa global} ({key:Ctrl} + {key:F}): pesquise em todos os grupos e clique num resultado para lá ir.\n• {bold:Seleção múltipla}: clique no ícone quadrado à direita.\n   - Mantenha {key:Shift} premida para selecionar um intervalo\n   - Use a barra inferior para {bold:eliminar}, {bold:mover} ou {bold:exportar} os dados selecionados.',
      step5Title: '⚙️ Cópias de segurança e definições', step5Message: 'A barra inferior mantém as ferramentas essenciais por perto.\n\n• {bold:Importar / Exportar}: exporte regularmente uma cópia de segurança JSON para proteger os dados.\n• {bold:Definições}: escolha o idioma, o tema, a localização inicial e as linhas de pré-visualização.\n• {bold:Ajuda}: clique no ponto de interrogação para voltar a abrir este guia.'
    },
    controls: { skip: 'Ignorar', back: 'Anterior', next: 'Seguinte', finish: 'Concluir' },
    demo: { groupName: '✨ Grupo do guia', categoryName: '📝 Categoria de exemplo', phraseTitle: '👋 Bem-vindo!', phraseContent: 'Esta é uma frase de exemplo. Clique para copiar ou experimente arrastá-la.', phraseTitle2: '⌨️ Atalhos de teclado', phraseContent2: 'Selecione-me e prima Ctrl+C para copiar, Ctrl+D para duplicar ou Delete para eliminar.', phraseTitle3: '🖱️ Arrastar e mover', phraseContent3: 'Mantenha premido e arraste-me para reordenar, ou largue-me noutra categoria à esquerda.' }
  }
}
