export default {
  app: { title: 'Менеджер фраз' },
  snackbar: {
    selectParentCategoryFirst: 'Сначала выберите группу', categoryDeleted: 'Категория удалена', categoryNameExists: 'Категория с таким названием уже существует', categoryCreated: 'Категория создана', categoryUpdated: 'Категория обновлена', groupNameExists: 'Группа с таким названием уже существует', groupCreated: 'Группа создана', groupUpdated: 'Группа обновлена', groupDeleted: 'Группа удалена', noGroup: 'Сначала создайте или выберите группу', undone: 'Действие отменено', redone: 'Действие повторено',
    noChanges: 'Нет изменений для сохранения', duplicatePhrase: 'Такая фраза уже существует', phraseCreated: 'Фраза создана', phraseUpdated: 'Изменения сохранены', phraseDeleted: 'Фраза удалена', titleEmpty: 'Название не может быть пустым', contentEmpty: 'Содержимое пусто', saveFailed: 'Не удалось сохранить. Повторите попытку.', copiedToClipboard: 'Скопировано в буфер обмена', createCategoryFirst: 'Сначала создайте категорию', itemsDeleted: { one: 'Удалён {count} элемент', few: 'Удалено {count} элемента', many: 'Удалено {count} элементов', other: 'Удалено {count} элемента' }, phrasesMoved: { one: 'Перемещена {count} фраза', few: 'Перемещено {count} фразы', many: 'Перемещено {count} фраз', other: 'Перемещено {count} фразы' }, movedToTop: 'Перемещено в начало', movedToBottom: 'Перемещено в конец', batchMovedToTop: 'Выбранные элементы перемещены в начало', batchMovedToBottom: 'Выбранные элементы перемещены в конец', phraseCloned: 'Фраза продублирована', clonedToCategory: 'Скопировано в новую категорию', movedToCategory: 'Перемещено в новую категорию',
    categoryCopiedToGroup: 'Категория скопирована в новую группу', categoryMovedToGroup: 'Категория перемещена в новую группу', categoriesCopiedToGroup: { one: 'В новую группу скопирована {count} категория', few: 'В новую группу скопировано {count} категории', many: 'В новую группу скопировано {count} категорий', other: 'В новую группу скопировано {count} категории' }, categoriesMovedToGroup: { one: 'В новую группу перемещена {count} категория', few: 'В новую группу перемещено {count} категории', many: 'В новую группу перемещено {count} категорий', other: 'В новую группу перемещено {count} категории' }, copiedToUncategorized: 'Скопировано в «Без категории»', movedToUncategorized: 'Перемещено в «Без категории»', phrasesCopiedToUncategorized: { one: 'В «Без категории» скопирована {count} фраза', few: 'В «Без категории» скопировано {count} фразы', many: 'В «Без категории» скопировано {count} фраз', other: 'В «Без категории» скопировано {count} фразы' }, phrasesMovedToUncategorized: { one: 'В «Без категории» перемещена {count} фраза', few: 'В «Без категории» перемещено {count} фразы', many: 'В «Без категории» перемещено {count} фраз', other: 'В «Без категории» перемещено {count} фразы' },
    exportSuccess: 'Экспорт завершён', exportFailed: 'Не удалось экспортировать: {error}', importSuccess: 'Импорт завершён. Категорий: {categories}; фраз: {phrases}', importFailed: 'Не удалось импортировать: {error}', batchExportSuccess: 'Экспорт завершён. Категорий: {categories}; фраз: {phrases}', iflytekImportSuccess: 'Импорт из метода ввода iFlytek завершён. Категорий: {categories}; фраз: {phrases}', iflytekExportSuccess: 'Экспортировано в формате метода ввода iFlytek', batchMovedToGroup: 'Перемещено в группу. Категорий: {categories}; фраз: {phrases}', guideCompleted: 'Обучение завершено! Мы добавили примеры данных, чтобы вы могли освоиться в приложении.', cloudUpdatedDraftPreserved: 'Данные в облаке обновились. Текущий черновик не был перезаписан.'
  },
  tooltip: { newCategory: 'Новая категория (Ctrl+Shift+N)', newPhrase: 'Новая фраза (Ctrl+N)', help: 'Справка', switchToLight: 'Светлая тема', switchToDark: 'Тёмная тема', import: 'Импорт', export: 'Экспорт', sort: 'Сортировка', batchMode: 'Выбрать несколько', selectAll: 'Выбрать всё / Снять выделение', moveToCategory: 'Переместить в категорию', moveToTop: 'Переместить в начало', moveToBottom: 'Переместить в конец', delete: 'Удалить', exit: 'Выйти', clone: 'Дублировать', edit: 'Изменить', newGroup: 'Новая группа', fullscreen: 'Полноэкранный редактор', exitFullscreen: 'Выйти из полноэкранного режима', exitEdit: 'Закрыть редактор', settings: 'Настройки' },
  menu: { rename: 'Переименовать', moveToTop: 'Переместить в начало', moveToBottom: 'Переместить в конец', delete: 'Удалить', copyContent: 'Копировать содержимое', clone: 'Дублировать', edit: 'Изменить', sortCustom: 'Пользовательский порядок', sortUsageDesc: 'Сначала часто используемые', sortUsageAsc: 'Сначала редко используемые', sortCreatedDesc: 'Сначала новые', sortCreatedAsc: 'Сначала старые', sortUpdatedDesc: 'Сначала недавно изменённые', sortUpdatedAsc: 'Сначала давно изменённые', sortTitleAsc: 'Название (А–Я)', sortTitleDesc: 'Название (Я–А)', newGroup: 'Новая группа…', newCategory: 'Новая категория…', exportNative: 'Экспортировать в JSON', exportIflytek: 'Экспортировать для метода ввода iFlytek' },
  label: { group: 'Группа', category: 'Категория', title: 'Название', content: 'Содержимое' }, placeholder: { searchPhrase: 'Поиск фраз…' }, empty: { noCategories: 'Категорий пока нет', quickJump: 'Перейти к категории', noResults: 'Совпадений нет', noPhrases: 'Фраз пока нет', noGroups: 'Групп пока нет', uncategorized: 'Без категории' },
  defaults: { groupName: 'Новая группа', newGroup: 'Новая группа', categoryName: 'Новая категория', newCategory: 'Новая категория', uncategorized: 'Без категории', newPhrase: 'Новая фраза', copySuffix: ' (копия)', iflytekGroupName: 'Из метода ввода iFlytek', importGroupName: 'Импортированные данные' },
  dialog: { unsavedChanges: 'Несохранённые изменения', unsavedContent: 'Это содержимое ещё не сохранено. Сохранить изменения?', unsavedContentNote: 'Несохранённые изменения будут потеряны.', discard: 'Не сохранять', thinkAgain: 'Продолжить редактирование', save: 'Сохранить', exportTitle: 'Экспорт резервной копии фраз', exportIflytekTitle: 'Экспорт для метода ввода iFlytek', importTitle: 'Импорт резервной копии фраз', jsonFilter: 'Файлы JSON', csvFilter: 'Файлы CSV', allSupportedFilter: 'Поддерживаемые файлы' },
  count: { categories: { one: '{count} категория', few: '{count} категории', many: '{count} категорий', other: '{count} категории' }, characters: { one: '{count} символ', few: '{count} символа', many: '{count} символов', other: '{count} символа' }, selected: { one: 'Выбран {count} элемент', few: 'Выбрано {count} элемента', many: 'Выбрано {count} элементов', other: 'Выбрано {count} элемента' }, batchSelected: 'Выбрано — категорий: {categories}; фраз: {phrases}' }, section: { groups: 'Группы фраз' }, file: { backupName: 'rezervnaya-kopiya-fraz-{date}.json', iflytekBackupName: 'rezervnaya-kopiya-fraz-{date}.csv' },
  common: { cancel: 'Отмена', apply: 'Применить', close: 'Закрыть', copy: 'Копировать', listSeparator: ', ', groupSeparator: '; ', labelSeparator: ': ' },
  settings: { title: 'Настройки', language: 'Язык интерфейса', languageAuto: 'Автоматически (язык системы)', themeMode: 'Тема', themeLight: 'Светлая', themeDark: 'Тёмная', themeAuto: 'Как в системе', startupSelection: 'Открывать при запуске', startupLast: 'Последнее открытое место', startupFirst: 'Первый элемент по порядку', previewLinesLabel: 'Строки предпросмотра карточки', previewLines: 'Строк в предпросмотре: {count}', aiModel: 'Модель ИИ', defaultAiModel: 'Модель по умолчанию', aiPrompts: 'Инструкции для ИИ', aiCategorizePrompt: 'Инструкция по классификации', aiTitlePrompt: 'Инструкция по созданию заголовка', aiContentPrompt: 'Инструкция по созданию текста', updated: 'Обновлено: {items}' },
  ai: {
    categorize: 'Распределить с помощью ИИ', generateTitle: 'Создать название с помощью ИИ', generateContent: 'Создать текст с помощью ИИ', optimizeContent: 'Улучшить текст с помощью ИИ', themeGeneration: 'Создать по теме', newGeneration: 'Создать заново', optimizeExisting: 'Улучшить текущий текст', useAsTheme: 'Использовать как тему', optimizeDescription: 'ИИ сделает текущий текст яснее и профессиональнее.', extraRequirementsLabel: 'Дополнительные указания (необязательно)', descriptionLabel: 'Опишите нужный текст', extraRequirementsPlaceholder: 'Например: сделай тон официальнее и добавь благодарность…', descriptionPlaceholder: 'Например: письмо с отказом от сверхурочной работы или благодарность клиенту…', contentApplied: 'Текст применён', generating: 'Создание…', startOptimize: 'Улучшить', generate: 'Создать', inputRequired: 'Сначала введите текст', titleGenerated: 'Название создано', categorized: 'Распределено в {group} / {category}', categorizedCategory: 'Распределено в {category}', categoryNotFound: 'Категория не найдена: {category}', groupNotFound: 'Группа не найдена: {group}', noSuggestion: 'ИИ не смог подобрать подходящую категорию', callFailed: 'Не удалось выполнить запрос к ИИ',
    prompt: { optimizeSystem: 'Вы — профессиональный редактор. Улучшите текст пользователя: сделайте его ясным, естественным, профессиональным и хорошо структурированным, не меняя смысл. Верните только отредактированный текст без пояснений.', themeSystem: 'Вы — профессиональный помощник по написанию текстов. Пользователь предоставит существующий текст в качестве темы. Напишите на его основе новую, естественную и профессиональную фразу для повторного использования. Верните только новый текст без пояснений.', themeUser: 'Тема:\n{content}\n\nНапишите новый текст на основе этой темы.{extra}', extraRequirements: '\nДополнительные указания: {prompt}', generateSystem: 'Вы — профессиональный помощник по написанию текстов. По описанию пользователя составьте краткую, естественную и профессиональную фразу для повторного использования. Верните только готовый текст без пояснений.', categorizeSystem: 'Вы — помощник по классификации. По содержанию выберите наиболее подходящую категорию верхнего уровня и одну из её групп в структуре ниже.\nСтруктура: {structure}\nВерните только JSON точно в таком формате: {"分类":"название категории","分组":"название группы"}', titleSystem: 'Вы — помощник по созданию названий. Придумайте краткое и точное название содержимого длиной не более 15 слов. Верните только название.' }
  },
  accessibility: { copyPhrase: '{title}. Нажмите Enter, чтобы скопировать содержимое.' }, dynamic: { group: 'Группа', category: 'Категория', phrase: 'Фраза', explain: 'Открыть или скопировать фразу' }, error: { emptyFile: 'Файл пуст', uncaught: 'Неперехваченная ошибка', unhandledPromise: 'Необработанная асинхронная ошибка', renderTitle: 'Ошибка отрисовки React' },
  help: {
    sectionHierarchy: '📚 Структура данных', hierarchyGroup: 'Группа', hierarchyGroupDesc: 'Верхний уровень', hierarchyCategory: 'Категория', hierarchyCategoryDesc: 'Папка для организации', hierarchyPhrase: 'Фраза', hierarchyPhraseDesc: 'Повторно используемый текст',
    sectionFeatures: '✨ Возможности', featureCopyTitle: 'Копирование одним щелчком', featureCopyDesc: 'Щёлкните карточку, чтобы скопировать её содержимое в буфер обмена и сразу вставить.', featureEditTitle: 'Быстрое редактирование', featureEditDesc: 'Наведите указатель на карточку и нажмите {key}, чтобы сразу её изменить.', featureDeleteTitle: 'Удаление и отмена', featureDeleteDesc: 'Наведите указатель и нажмите {delKey}, чтобы удалить, или {ctrlKey}+{zKey}, чтобы отменить.', featureDragTitle: 'Перетаскивание', featureDragDesc: 'Перетащите карточку в нужную категорию. Удерживайте {key} при перетаскивании, чтобы скопировать её.', featureSearchTitle: 'Поиск везде', featureSearchDesc: 'Ищите во всех группах и щёлкните результат, чтобы сразу перейти к нему.', featureBatchTitle: 'Выбор нескольких элементов', featureBatchDesc: 'Используйте квадратный значок рядом с поиском, чтобы выбрать, удалить, переместить или экспортировать несколько элементов.', featurePreviewTitle: 'Режим предпросмотра', featurePreviewDesc: 'Наведите указатель на карточку и один раз нажмите {key}, чтобы включить или выключить предпросмотр. Переключайтесь между карточками стрелками вверх и вниз.', featureAutoSaveTitle: 'Автосохранение', featureAutoSaveDesc: 'После редактирования щёлкните вне редактора или перейдите к другой карточке — изменения сохранятся автоматически.', featureThemeTitle: 'Тема', featureThemeDesc: 'В Настройках можно выбрать светлую или тёмную тему либо использовать системную.',
    sectionShortcuts: '⌨️ Сочетания клавиш', shortcutNewPhrase: 'Новая фраза', shortcutNewCategory: 'Новая категория', shortcutFocusSearch: 'Перейти к поиску', shortcutForceSave: 'Сохранить сейчас', shortcutUndo: 'Отменить', shortcutRedo: 'Повторить', shortcutSelectAll: 'Выбрать всё (множественный выбор)', shortcutClone: 'Дублировать элемент под указателем', shortcutCopy: 'Копировать элемент под указателем', shortcutEdit: 'Изменить элемент под указателем', shortcutDelete: 'Удалить элемент под указателем', shortcutEscape: 'Выйти / Отменить', shortcutFullscreen: 'Полноэкранный редактор', shortcutPreview: 'Переключить предпросмотр', shortcutDragCopy: 'Копировать в место назначения', dragAction: 'Перетащить', startGuide: 'Запустить обучение'
  },
  guide: {
    steps: {
      step1Title: '🗂️ Группы (верхний уровень)', step1Message: 'Группы разделяют крупные области работы.\n\n• {bold:Создать}: нажмите кнопку {key:+} вверху.\n• {bold:Переключить}: щёлкните группу, чтобы показать её категории.\n• {bold:Изменить порядок}: удерживайте группу и перетащите её влево или вправо.\n• {bold:Дополнительно}: щёлкните группу правой кнопкой, чтобы {bold:переименовать}, {bold:удалить} или изменить её положение.',
      step2Title: '📂 Категории и контекстное меню', step2Message: 'В этом столбце показаны категории текущей группы.\n\n• {bold:Создать категорию}: откройте список категорий, выберите «Новая категория…», введите своё название и подтвердите; сначала создайте или выберите группу.\n• {bold:Контекстное меню}: щёлкните категорию правой кнопкой, чтобы {bold:переименовать}, {bold:переместить в начало} или {bold:удалить}.\n• {bold:Быстрое переименование}: выберите категорию и нажмите {key:F2}.\n• {bold:Перетаскивание}: перетащите вверх или вниз для изменения порядка либо бросьте категорию на другую группу, чтобы переместить её.\n• {bold:Правила названий}: название не может быть пустым; при совпадении появится предупреждение.',
      step3Title: '📝 Работа с фразами', step3Message: 'Это основная рабочая область.\n\n• {bold:Копирование}: щёлкните карточку, чтобы скопировать содержимое.\n• {bold:Сочетания клавиш}:\n   - {key:Ctrl} + {key:C} — копировать\n   - {key:Ctrl} + {key:D} — дублировать\n   - {key:Del} — удалить выбранное\n• {bold:Изменение порядка}: перетаскивайте карточки вверх и вниз.\n• {bold:Перемещение между категориями}: бросьте карточку на категорию слева; удерживайте {key:Ctrl}, чтобы скопировать её.\n• {bold:Предпросмотр}: наведите указатель на карточку, один раз нажмите {key:Пробел}, затем используйте стрелки вверх и вниз.',
      step4Title: '🔍 Поиск и множественный выбор', step4Message: 'Верхняя панель предоставляет доступ ко всему содержимому.\n\n• {bold:Глобальный поиск} ({key:Ctrl} + {key:F}): ищите во всех группах и щёлкните результат, чтобы перейти к нему.\n• {bold:Множественный выбор}: щёлкните квадратный значок справа.\n   - Удерживайте {key:Shift}, чтобы выбрать диапазон\n   - На нижней панели можно {bold:удалить}, {bold:переместить} или {bold:экспортировать} выбранные данные.',
      step5Title: '⚙️ Резервные копии и настройки', step5Message: 'На нижней панели находятся основные инструменты.\n\n• {bold:Импорт / Экспорт}: регулярно экспортируйте резервную копию JSON, чтобы защитить данные.\n• {bold:Настройки}: выберите язык, тему, начальное расположение и число строк предпросмотра.\n• {bold:Справка}: щёлкните вопросительный знак, чтобы снова открыть это обучение.'
    },
    controls: { skip: 'Пропустить', back: 'Назад', next: 'Далее', finish: 'Готово' },
    demo: { groupName: '✨ Учебная группа', categoryName: '📝 Пример категории', phraseTitle: '👋 Добро пожаловать!', phraseContent: 'Это пример фразы. Щёлкните, чтобы скопировать её, или попробуйте перетащить.', phraseTitle2: '⌨️ Сочетания клавиш', phraseContent2: 'Выберите меня и нажмите Ctrl+C, чтобы скопировать, Ctrl+D, чтобы дублировать, или Delete, чтобы удалить.', phraseTitle3: '🖱️ Перетаскивание', phraseContent3: 'Удерживайте и перетащите меня, чтобы изменить порядок, или бросьте на другую категорию слева.' }
  }
}
