export default {
  app: { title: 'Trình quản lý mẫu câu' },
  snackbar: {
    selectParentCategoryFirst: 'Hãy chọn một nhóm trước', categoryDeleted: 'Đã xóa danh mục', categoryNameExists: 'Tên danh mục này đã tồn tại', categoryCreated: 'Đã tạo danh mục', categoryUpdated: 'Đã cập nhật danh mục', groupNameExists: 'Tên nhóm này đã tồn tại', groupCreated: 'Đã tạo nhóm', groupUpdated: 'Đã cập nhật nhóm', groupDeleted: 'Đã xóa nhóm', noGroup: 'Hãy tạo hoặc chọn một nhóm trước', undone: 'Đã hoàn tác thao tác', redone: 'Đã làm lại thao tác',
    noChanges: 'Không có thay đổi nào', duplicatePhrase: 'Mẫu câu này đã tồn tại', phraseCreated: 'Đã tạo mẫu câu', phraseUpdated: 'Đã lưu thay đổi', phraseDeleted: 'Đã xóa mẫu câu', titleEmpty: 'Tiêu đề không được để trống', contentEmpty: 'Nội dung đang để trống', saveFailed: 'Không thể lưu. Vui lòng thử lại.', copiedToClipboard: 'Đã sao chép vào bảng nhớ tạm', createCategoryFirst: 'Hãy tạo một danh mục trước', itemsDeleted: 'Đã xóa {count} mục', phrasesMoved: 'Đã di chuyển {count} mẫu câu', movedToTop: 'Đã đưa lên đầu', movedToBottom: 'Đã đưa xuống cuối', batchMovedToTop: 'Đã đưa các mục đã chọn lên đầu', batchMovedToBottom: 'Đã đưa các mục đã chọn xuống cuối', phraseCloned: 'Đã nhân bản mẫu câu', clonedToCategory: 'Đã sao chép sang danh mục mới', movedToCategory: 'Đã di chuyển sang danh mục mới',
    categoryCopiedToGroup: 'Đã sao chép danh mục sang nhóm mới', categoryMovedToGroup: 'Đã di chuyển danh mục sang nhóm mới', categoriesCopiedToGroup: 'Đã sao chép {count} danh mục sang nhóm mới', categoriesMovedToGroup: 'Đã di chuyển {count} danh mục sang nhóm mới', copiedToUncategorized: 'Đã sao chép vào “Chưa phân loại”', movedToUncategorized: 'Đã di chuyển vào “Chưa phân loại”', phrasesCopiedToUncategorized: 'Đã sao chép {count} mẫu câu vào “Chưa phân loại”', phrasesMovedToUncategorized: 'Đã di chuyển {count} mẫu câu vào “Chưa phân loại”',
    exportSuccess: 'Xuất dữ liệu thành công', exportFailed: 'Không thể xuất dữ liệu: {error}', importSuccess: 'Đã nhập {categories} danh mục và {phrases} mẫu câu', importFailed: 'Không thể nhập dữ liệu: {error}', batchExportSuccess: 'Đã xuất {categories} danh mục và {phrases} mẫu câu', iflytekImportSuccess: 'Đã nhập từ bộ gõ iFlytek: {categories} danh mục và {phrases} mẫu câu', iflytekExportSuccess: 'Đã xuất theo định dạng bộ gõ iFlytek', batchMovedToGroup: 'Đã chuyển vào nhóm: {categories} danh mục và {phrases} mẫu câu', guideCompleted: 'Bạn đã hoàn tất phần hướng dẫn! Dữ liệu mẫu đã sẵn sàng để bạn khám phá.', cloudUpdatedDraftPreserved: 'Dữ liệu trên đám mây đã được cập nhật. Bản nháp hiện tại của bạn vẫn được giữ nguyên.'
  },
  tooltip: { newCategory: 'Danh mục mới (Ctrl+Shift+N)', newPhrase: 'Mẫu câu mới (Ctrl+N)', help: 'Trợ giúp', switchToLight: 'Giao diện sáng', switchToDark: 'Giao diện tối', import: 'Nhập dữ liệu', export: 'Xuất dữ liệu', sort: 'Sắp xếp', batchMode: 'Chọn nhiều mục', selectAll: 'Chọn tất cả / Bỏ chọn', moveToCategory: 'Chuyển sang danh mục', moveToTop: 'Đưa lên đầu', moveToBottom: 'Đưa xuống cuối', delete: 'Xóa', exit: 'Thoát', clone: 'Nhân bản', edit: 'Chỉnh sửa', newGroup: 'Nhóm mới', fullscreen: 'Soạn thảo toàn màn hình', exitFullscreen: 'Thoát toàn màn hình', exitEdit: 'Đóng trình soạn thảo', settings: 'Cài đặt' },
  menu: { rename: 'Đổi tên', moveToTop: 'Đưa lên đầu', moveToBottom: 'Đưa xuống cuối', delete: 'Xóa', copyContent: 'Sao chép nội dung', clone: 'Nhân bản', edit: 'Chỉnh sửa', sortCustom: 'Thứ tự tùy chỉnh', sortUsageDesc: 'Dùng nhiều nhất trước', sortUsageAsc: 'Dùng ít nhất trước', sortCreatedDesc: 'Mới tạo trước', sortCreatedAsc: 'Cũ nhất trước', sortUpdatedDesc: 'Mới sửa trước', sortUpdatedAsc: 'Sửa lâu nhất trước', sortTitleAsc: 'Tiêu đề (A–Z)', sortTitleDesc: 'Tiêu đề (Z–A)', newGroup: 'Nhóm mới…', newCategory: 'Danh mục mới…', exportNative: 'Xuất dưới dạng JSON', exportIflytek: 'Xuất cho bộ gõ iFlytek' },
  label: { group: 'Nhóm', category: 'Danh mục', title: 'Tiêu đề', content: 'Nội dung' }, placeholder: { searchPhrase: 'Tìm mẫu câu…' },
  empty: { noCategories: 'Chưa có danh mục', quickJump: 'Chuyển nhanh đến danh mục', noResults: 'Không có kết quả phù hợp', noPhrases: 'Chưa có mẫu câu', noGroups: 'Chưa có nhóm', uncategorized: 'Chưa phân loại' },
  defaults: { groupName: 'Nhóm mới', newGroup: 'Nhóm mới', categoryName: 'Danh mục mới', newCategory: 'Danh mục mới', uncategorized: 'Chưa phân loại', newPhrase: 'Mẫu câu mới', copySuffix: ' (bản sao)', iflytekGroupName: 'Từ bộ gõ iFlytek', importGroupName: 'Dữ liệu đã nhập' },
  dialog: { unsavedChanges: 'Thay đổi chưa được lưu', unsavedContent: 'Nội dung này chưa được lưu. Bạn có muốn lưu thay đổi không?', unsavedContentNote: 'Mọi thay đổi chưa lưu sẽ bị mất.', discard: 'Không lưu', thinkAgain: 'Tiếp tục chỉnh sửa', save: 'Lưu', exportTitle: 'Xuất bản sao lưu mẫu câu', exportIflytekTitle: 'Xuất cho bộ gõ iFlytek', importTitle: 'Nhập bản sao lưu mẫu câu', jsonFilter: 'Tệp JSON', csvFilter: 'Tệp CSV', allSupportedFilter: 'Tệp được hỗ trợ' },
  count: { categories: '{count} danh mục', characters: '{count} ký tự', selected: 'Đã chọn {count} mục', batchSelected: 'Đã chọn {categories} danh mục và {phrases} mẫu câu' }, section: { groups: 'Nhóm mẫu câu' }, file: { backupName: 'ban-sao-luu-mau-cau-{date}.json', iflytekBackupName: 'ban-sao-luu-mau-cau-{date}.csv' },
  common: { cancel: 'Hủy', apply: 'Áp dụng', close: 'Đóng', copy: 'Sao chép', listSeparator: ', ', groupSeparator: '; ', labelSeparator: ': ' },
  settings: { title: 'Cài đặt', language: 'Ngôn ngữ hiển thị', languageAuto: 'Tự động (theo hệ thống)', themeMode: 'Giao diện', themeLight: 'Sáng', themeDark: 'Tối', themeAuto: 'Theo hệ thống', startupSelection: 'Mở khi khởi động', startupLast: 'Vị trí xem gần nhất', startupFirst: 'Mục đầu tiên theo thứ tự', previewLinesLabel: 'Số dòng xem trước trên thẻ', previewLines: 'Số dòng xem trước trên thẻ: {count}', aiModel: 'Mô hình AI', defaultAiModel: 'Mô hình mặc định', aiPrompts: 'Câu lệnh AI', aiCategorizePrompt: 'Câu lệnh phân loại', aiTitlePrompt: 'Câu lệnh tạo tiêu đề', aiContentPrompt: 'Câu lệnh tạo nội dung', updated: 'Đã cập nhật: {items}' },
  ai: {
    categorize: 'Phân loại bằng AI', generateTitle: 'Tạo tiêu đề bằng AI', generateContent: 'Tạo nội dung bằng AI', optimizeContent: 'Cải thiện nội dung bằng AI', themeGeneration: 'Tạo theo chủ đề bằng AI', newGeneration: 'Tạo nội dung mới', optimizeExisting: 'Cải thiện nội dung hiện có', useAsTheme: 'Dùng làm chủ đề', optimizeDescription: 'AI sẽ giúp nội dung hiện có rõ ràng và chuyên nghiệp hơn.', extraRequirementsLabel: 'Yêu cầu thêm (không bắt buộc)', descriptionLabel: 'Mô tả nội dung bạn cần', extraRequirementsPlaceholder: 'Ví dụ: dùng giọng điệu trang trọng hơn và thêm lời cảm ơn…', descriptionPlaceholder: 'Ví dụ: email từ chối làm thêm giờ hoặc lời cảm ơn khách hàng…', contentApplied: 'Đã áp dụng nội dung', generating: 'Đang tạo…', startOptimize: 'Cải thiện', generate: 'Tạo', inputRequired: 'Hãy nhập nội dung trước', titleGenerated: 'Đã tạo tiêu đề', categorized: 'Đã phân loại vào {group} / {category}', categorizedCategory: 'Đã phân loại vào {category}', categoryNotFound: 'Không tìm thấy danh mục: {category}', groupNotFound: 'Không tìm thấy nhóm: {group}', noSuggestion: 'AI không tìm được danh mục phù hợp', callFailed: 'Yêu cầu AI không thành công',
    prompt: { optimizeSystem: 'Bạn là biên tập viên chuyên nghiệp. Hãy chỉnh sửa văn bản của người dùng để nội dung rõ ràng, mạch lạc và chuyên nghiệp hơn mà không làm thay đổi ý nghĩa. Chỉ trả về văn bản đã chỉnh sửa, không giải thích thêm.', themeSystem: 'Bạn là trợ lý viết nội dung chuyên nghiệp. Người dùng sẽ cung cấp một đoạn văn bản hiện có làm chủ đề. Hãy viết một mẫu câu mới, tự nhiên và chuyên nghiệp dựa trên chủ đề đó. Chỉ trả về nội dung mới, không giải thích thêm.', themeUser: 'Chủ đề:\n{content}\n\nHãy tạo nội dung mới dựa trên chủ đề này.{extra}', extraRequirements: '\nYêu cầu thêm: {prompt}', generateSystem: 'Bạn là trợ lý viết nội dung chuyên nghiệp. Hãy tạo một mẫu câu ngắn gọn, tự nhiên và chuyên nghiệp theo mô tả của người dùng. Chỉ trả về nội dung được tạo, không giải thích thêm.', categorizeSystem: 'Bạn là trợ lý phân loại. Dựa trên nội dung, hãy chọn danh mục phù hợp nhất và một nhóm trực thuộc danh mục đó từ cấu trúc bên dưới.\nCấu trúc: {structure}\nChỉ trả về JSON theo đúng định dạng sau: {"分类":"tên danh mục","分组":"tên nhóm"}', titleSystem: 'Bạn là trợ lý đặt tiêu đề. Hãy viết một tiêu đề ngắn gọn, chính xác cho nội dung, không quá 15 từ. Chỉ trả về tiêu đề.' }
  },
  accessibility: { copyPhrase: '{title}. Nhấn Enter để sao chép nội dung.' }, dynamic: { group: 'Nhóm', category: 'Danh mục', phrase: 'Mẫu câu', explain: 'Mở hoặc sao chép mẫu câu' }, error: { emptyFile: 'Tệp đang để trống', uncaught: 'Lỗi chưa được bắt', unhandledPromise: 'Lỗi bất đồng bộ chưa được xử lý', renderTitle: 'Lỗi hiển thị React' },
  help: {
    sectionHierarchy: '📚 Cách tổ chức dữ liệu', hierarchyGroup: 'Nhóm', hierarchyGroupDesc: 'Cấp cao nhất', hierarchyCategory: 'Danh mục', hierarchyCategoryDesc: 'Thư mục sắp xếp', hierarchyPhrase: 'Mẫu câu', hierarchyPhraseDesc: 'Nội dung dùng lại',
    sectionFeatures: '✨ Tính năng', featureCopyTitle: 'Sao chép bằng một lần bấm', featureCopyDesc: 'Bấm vào thẻ bất kỳ để sao chép nội dung vào bảng nhớ tạm và dán ngay khi cần.', featureEditTitle: 'Chỉnh sửa nhanh', featureEditDesc: 'Di chuột lên thẻ rồi nhấn {key} để chỉnh sửa ngay.', featureDeleteTitle: 'Xóa và hoàn tác', featureDeleteDesc: 'Khi đang di chuột, nhấn {delKey} để xóa hoặc {ctrlKey}+{zKey} để hoàn tác.', featureDragTitle: 'Kéo để di chuyển', featureDragDesc: 'Kéo thẻ vào danh mục đích. Giữ {key} trong khi kéo để sao chép.', featureSearchTitle: 'Tìm kiếm toàn bộ', featureSearchDesc: 'Tìm trong mọi nhóm, rồi bấm vào kết quả để chuyển thẳng đến vị trí đó.', featureBatchTitle: 'Chọn nhiều mục', featureBatchDesc: 'Dùng biểu tượng hình vuông cạnh ô tìm kiếm để chọn, xóa, di chuyển hoặc xuất nhiều mục cùng lúc.', featurePreviewTitle: 'Chế độ xem trước', featurePreviewDesc: 'Di chuột lên thẻ rồi nhấn {key} một lần để bật hoặc tắt chế độ xem trước. Dùng phím mũi tên Lên và Xuống để chuyển thẻ.', featureAutoSaveTitle: 'Tự động lưu', featureAutoSaveDesc: 'Sau khi chỉnh sửa, bấm ra ngoài hoặc chuyển sang thẻ khác để tự động lưu.', featureThemeTitle: 'Giao diện', featureThemeDesc: 'Mở Cài đặt để chọn giao diện sáng, tối hoặc theo hệ thống.',
    sectionShortcuts: '⌨️ Phím tắt', shortcutNewPhrase: 'Mẫu câu mới', shortcutNewCategory: 'Danh mục mới', shortcutFocusSearch: 'Chuyển đến ô tìm kiếm', shortcutForceSave: 'Lưu ngay', shortcutUndo: 'Hoàn tác', shortcutRedo: 'Làm lại', shortcutSelectAll: 'Chọn tất cả (chế độ chọn nhiều)', shortcutClone: 'Nhân bản mục đang trỏ tới', shortcutCopy: 'Sao chép mục đang trỏ tới', shortcutEdit: 'Sửa mục đang trỏ tới', shortcutDelete: 'Xóa mục đang trỏ tới', shortcutEscape: 'Thoát / Hủy', shortcutFullscreen: 'Soạn thảo toàn màn hình', shortcutPreview: 'Bật/tắt chế độ xem trước', shortcutDragCopy: 'Sao chép đến đích', dragAction: 'Kéo', startGuide: 'Bắt đầu hướng dẫn'
  },
  guide: {
    steps: {
      step1Title: '🗂️ Nhóm (cấp cao nhất)', step1Message: 'Nhóm giúp bạn tách riêng các loại công việc lớn.\n\n• {bold:Tạo}: bấm nút {key:+} ở phía trên.\n• {bold:Chuyển}: bấm vào một nhóm để xem các danh mục của nhóm đó.\n• {bold:Sắp xếp}: nhấn giữ rồi kéo nhóm sang trái hoặc phải.\n• {bold:Thêm}: bấm chuột phải vào nhóm để {bold:đổi tên}, {bold:xóa} hoặc đổi vị trí.',
      step2Title: '📂 Danh mục và trình đơn chuột phải', step2Message: 'Cột này hiển thị các danh mục trong nhóm hiện tại.\n\n• {bold:Tạo danh mục}: mở danh sách danh mục, chọn “Danh mục mới…”, nhập tên tùy chỉnh rồi xác nhận; hãy tạo hoặc chọn một nhóm trước.\n• {bold:Trình đơn chuột phải}: bấm chuột phải vào danh mục để {bold:đổi tên}, {bold:đưa lên đầu} hoặc {bold:xóa}.\n• {bold:Đổi tên nhanh}: chọn danh mục rồi nhấn {key:F2}.\n• {bold:Kéo thả}: kéo lên hoặc xuống để sắp xếp; thả vào nhóm khác để di chuyển sang nhóm đó.\n• {bold:Quy tắc tên}: không được để trống; tên trùng sẽ hiện cảnh báo.',
      step3Title: '📝 Thao tác với mẫu câu', step3Message: 'Đây là khu vực làm việc chính.\n\n• {bold:Sao chép}: bấm vào thẻ để sao chép nội dung.\n• {bold:Phím tắt}:\n   - {key:Ctrl} + {key:C} để sao chép\n   - {key:Ctrl} + {key:D} để nhân bản\n   - {key:Del} để xóa mục đã chọn\n• {bold:Sắp xếp}: kéo thẻ lên hoặc xuống.\n• {bold:Di chuyển giữa các danh mục}: thả thẻ vào danh mục bên trái; giữ {key:Ctrl} khi kéo để sao chép.\n• {bold:Xem trước}: di chuột lên thẻ, nhấn {key:Space} một lần rồi dùng phím mũi tên Lên và Xuống.',
      step4Title: '🔍 Tìm kiếm và chọn nhiều mục', step4Message: 'Thanh công cụ phía trên giúp bạn truy cập mọi nội dung.\n\n• {bold:Tìm kiếm toàn bộ} ({key:Ctrl} + {key:F}): tìm trong mọi nhóm rồi bấm vào kết quả để chuyển đến đó.\n• {bold:Chọn nhiều mục}: bấm biểu tượng hình vuông ở bên phải.\n   - Giữ {key:Shift} để chọn một dải\n   - Dùng thanh công cụ phía dưới để {bold:xóa}, {bold:di chuyển} hoặc {bold:xuất} dữ liệu đã chọn.',
      step5Title: '⚙️ Sao lưu và cài đặt', step5Message: 'Thanh công cụ phía dưới chứa các chức năng thiết yếu.\n\n• {bold:Nhập / Xuất}: nên xuất bản sao lưu JSON định kỳ để bảo vệ dữ liệu.\n• {bold:Cài đặt}: chọn ngôn ngữ, giao diện, vị trí mở khi khởi động và số dòng xem trước.\n• {bold:Trợ giúp}: bấm dấu hỏi để mở lại phần hướng dẫn này.'
    },
    controls: { skip: 'Bỏ qua', back: 'Quay lại', next: 'Tiếp', finish: 'Hoàn tất' },
    demo: { groupName: '✨ Nhóm hướng dẫn', categoryName: '📝 Danh mục mẫu', phraseTitle: '👋 Chào mừng bạn!', phraseContent: 'Đây là một mẫu câu minh họa. Hãy bấm để sao chép hoặc thử kéo thẻ.', phraseTitle2: '⌨️ Mẹo dùng phím tắt', phraseContent2: 'Chọn tôi rồi nhấn Ctrl+C để sao chép, Ctrl+D để nhân bản hoặc Delete để xóa.', phraseTitle3: '🖱️ Kéo và di chuyển', phraseContent3: 'Nhấn giữ rồi kéo tôi để sắp xếp hoặc thả vào một danh mục khác ở bên trái.' }
  }
}
